### ISSUE TITLE
wit-parser: always parse the file as if it's in a package

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wasm-tools#1018]
This is a feature request to ask wit-parser to always treat a wit file as if it's living in a wit package. That is, when a wit file path is given to the parser, it assumes that the current directory of the file is it's wit package, and thus parse from there. 

## How current wit-parser works on a path

The current way `wasm-tools component wit <path>` works is that it treats <path> differently depends on if it's a file or a directory. 
- If <path> is a file: then it uses `UnresolvedPackage::parse` to parse the file
- If <path> is a directory: it uses `Resolve::push_dir` to parse the directory, which uses `UnresolvedPackage::parse_dir` to parse the directory. 

For example, this is how the error message looks like when feeding `bad-diamond` to `wasm-tools component wit`

```shell
➜  ./target/release/wasm-tools component wit ./crates/wit-parser/tests/ui/parse-fail/bad-diamond         
Error: import of `shared`
  .. which is depended on by import `b`
conflicts with a previous interface using the name `shared`

     --> ./crates/wit-parser/tests/ui/parse-fail/bad-diamond/join.wit:3:10
      |
    3 |   import b: pkg.b
      |          ^
➜  ./target/release/wasm-tools component wit ./crates/wit-parser/tests/ui/parse-fail/bad-diamond/join.wit 
Error: document `a` does not exist
     --> ./crates/wit-parser/tests/ui/parse-fail/bad-diamond/join.wit:2:17
      |
    2 |   import a: pkg.a
      |                 ^
```

Take a closer look at that the only difference is on the path given to the wit-parser. One is a directory and another one is a wit file. 

## Feature Request

I believe it will be less confusing for users to see a consistent error message no matter if the path given is a file path or a directory path. If the path is a file path, wit-parser can first parse using `UnresolvedPackage::parse`, and then fall back to `UnresolvedPackage::parse_dir` where it uses the folder directory of that wit file to parse.

**Comment by alexcrichton** [comment]
If I understand this right, I think that this would be largely considered "fixed" with internal restructuring required to implement https://github.com/WebAssembly/component-model/issues/193. Mostly that documents as a concept will go away so errors will improve and single-file packages are more well-defined.

**Comment by alexcrichton** [comment]
I think this is fixed now or at least the issues in play are different enough that the context here isn't quite as applicable as before. @Mossaka are there still things you think this should track or would this be ok to close?

**Comment by Mossaka** [comment]
I am okay to close. Thanks!
