### ISSUE TITLE
Pass in the expected kind of ref that we are checking when validating

### ISSUE THREAD

**Issue by imikushin** [bytecodealliance/wasm-tools#1039]
When validating, sometimes we need to check the type of reference, e.g. when it's supposed to be a func.

              Yeah I suspect we will need different variations of this function for funcrefs vs other refs. Eg the `call_ref` instruction will need to be validated with something like this but which additionally checks that the type at the given index is actually a function. And similar for tables, we need to pass in the expected kind of ref that we are checking.

I think we can do this in a follow up though. Can you file an issue to track this Ivan?

_Originally posted by @fitzgen in https://github.com/bytecodealliance/wasm-tools/pull/1022#discussion_r1195514592_

**Comment by alexcrichton** [comment]
I think that this is now resolved with the gc proposal being implemented, so closing
