### ISSUE TITLE
component-type version 2 does not match supported version 3

### ISSUE THREAD

**Issue by tachyonicbytes** [bytecodealliance/wasm-tools#1069]
Hi! I am getting this error message, when I try to run the `wit-bindgen` host [example](https://github.com/bytecodealliance/wit-bindgen) with the latest versions:
```
$ wasm-tools component new ./target/wasm32-wasi
/debug/rust.wasm     -o my-component.wasm --adapt ./wasi_snapshot_preview1.wasm
error: decoding custom section component-type:command

Caused by:
    0: component-type version 2 does not match supported version 3
```

where `wasi_snapshot_preview1.wasm` is the command adapter.

I have investigated a bit, and it seems that the component-type version was changed in wasm-tools in version 1.0.34. I got the 1.0.33 and tried to run the component, but I got the reverse error message:

```
wasm-tools-1.0.33-x86_64
-linux/wasm-tools component new ./target/wasm32-wasi/debug/rust.wasm     -o my-component.wasm --adapt ./wasi
_snapshot_preview1.wasm
error: decoding custom section component-type:host

Caused by:
    0: component-type version 3 does not match supported version 2
```

which made me unsure of what I am doing wrong, because I don't know how to get the component version to see for myself. I tried searching into the `wit-bindgen` crate as well, but I could not see where it sets the version.

Apart from the issue itself, is there any easier way to test creating a wasm component? A pre-made repo, or something? I cannot find anything on the web, apart from the `wit-bindgen` example.

Versions:
```
$ wasm-tools --version
wasm-tools 1.0.35 (694d20d0f 2023-06-13)

wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.7.0" }
```

**Comment by alexcrichton** [comment]
What may be happening here is that you've got two core wasm binaries going into the creation of the component, your `rust.wasm` and the `wasi_snapshot_preview1.wasm`. One may have version 2 and one may have version 3. That means if you use a version 3 parser it'll fail on one, and if you use a version 2 parser it'll fail on the other one. I'd recommend bringing everything up-to-date with the latest versions of tools to ensure that everything works.

> Apart from the issue itself, is there any easier way to test creating a wasm component?

Unfortunately not at this time, but as all of the tooling here continues to develop and improve this will emerge over time.

**Comment by tachyonicbytes** [comment]
Yeah, this seems to have been it. For anyone reading, this https://github.com/bytecodealliance/wasmtime/releases/tag/dev is the place to get the latest adapters.

I will try to add it to the documentation as well, so others can see it there, when I get the time.
