### ISSUE TITLE
Inconsistent naming in wast::Instructions

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasm-tools#107]
Noticed that some instruction names are inconsistent, e.g. `I16x8WidenHighI8x16u` vs `I16x8WidenLowI8x16U` (last U), or with `wasmparser`, e.g. `V128Andnot`.

**Comment by alexcrichton** [comment]
Oops I think those are my mistake! Seems fine to fix though!

**Comment by darinmorrison** [comment]
I can submit a PR for this soon if nobody else gets it to first.

Regarding `V128Andnot`, I notice this is also the casing used in `wabt`. In this case, maybe it's okay because the instruction is `v128.andnot` instead of `v128.and_not`?

**Comment by alexcrichton** [comment]
I think thes ehave since largely been fixed, but if there's anything remaining it'd be great to fix through a PR!
