### ISSUE TITLE
wasmparser: "duplicate identifier for field" in subtype

### ISSUE THREAD

**Issue by patrick96** [bytecodealliance/wasm-tools#1092]
For the following module:

```wast
(module
    (type $A (struct (field $vt (mut i32))))
    (type $B (sub $A (struct (field $vt (mut i32)))))
)
```

I get the following output:

```
$ wasm-tools parse demo.wat                                              

error: duplicate identifier for field
     --> demo.wat:3:37
      |
    3 |     (type $B (sub $A (struct (field $vt (mut i32)))))
      |                                     ^
```

For subtypes, the same field in the subtype has to have the same name as in the supertype, otherwise it's impossible to do any kind of field manipulation unless you know the exact type of the object.

In fact, the spec for the gc proposal says:

> For fields, names need only be unique within a single type.
> -- [*`document/core/text/conventions.rst`*](https://github.com/WebAssembly/gc/blob/942c77f128a689bc09dac72059d392769ee71dde/document/core/text/conventions.rst)

---

This happens both on `main` (0263c2f2e0a33fe97569535aa2784b7989cb1dd0) and version 1.0.35.

**Comment by fitzgen** [comment]
Thanks for filing an issue!

Just a heads up, our GC support is very much still a work in progress.

**Comment by fitzgen** [comment]
cc @imikushin

**Comment by patrick96** [comment]
> Just a heads up, our GC support is very much still a work in progress.

Like most other tooling out there ;)

Appreciate your work on this

**Comment by imikushin** [comment]
Okay, the fix above will work, but with one caveat: field namespace is global per module. 

So, current limitation: fields with the same name can only be at the same position, even in totally different structs 😅

**Comment by patrick96** [comment]
> So, current limitation: fields with the same name can only be at the same position, even in totally different structs 😅

This works for my use-case since field names are distinct in unrelated structs. But I guess the spec won't allow for this limitation.

Also, with #1059 I am able to successfully assemble my webassembly text file (at least at the current state, my codegen is still missing a ton of things).

**Comment by imikushin** [comment]
@patrick96 unfortunately, by @alexcrichton 's suggestion, I had to remove the temporary dirty fix from #1059 . Good news is I'm going to send a proper fix after #1059 is merged.

**Comment by patrick96** [comment]
That's fine, keep doing what you're doing :)

**Comment by imikushin** [comment]
Submitted a fix ⬆️

**Comment by patrick96** [comment]
Awesome! Thanks for all your efforts
