### ISSUE TITLE
wasm_encoder: how to lift code module function?

### ISSUE THREAD

**Issue by stephanos** [bytecodealliance/wasm-tools#1093]
I'm playing around with generating byte code with the new Component Model and while I understand that it's the bleeding edge and changing a lot, I just can't get this one piece with the `CanonicalFunctionSection` to work and was wondering what I'm doing wrong (which is more likely than the code being wrong).

I tried to generate the simplest possible component I could think of (largely borrowed from https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md):

```wasm
(component
    (core module (;0;)
        (type (;0;) (func (result i32)))
        (func (;0;) (type 0) (result i32)
        i32.const 6
        i32.const 6
        i32.mul
        )
        (export "main" (func 0))
    )
    (type (;0;) (func (result s32)))
    (core instance $main (;0;) (instantiate 0))
    (func $main (;0;) (type 0) (canon lift (core func $main) string-encoding=utf8))
    (export (;1;) "main" (func $main))
)
```

Which _almost_ works. It's _so_ close! All that's needed is to change `(core func $main)` to `(core func $main "main")`. But I don't understand how to make this work with the current API - this is the relevant piece of code (which generates the line in question):

```rust
let mut functions = CanonicalFunctionSection::new();
functions.lift(0, 0, [CanonicalOption::UTF8]);
component.section(&functions);
```

I don't understand how I can use the API to reference and lift the $main instance's "main" function here.

I'd be grateful for any pointers! I'm sure I'm missing something.

**Comment by stephanos** [comment]
(if it's helpful, I posted the rest of the component model-specific Rust code [here](https://gist.github.com/stephanos/195b2b5da1fc2481f6055d368d815fc7))

**Comment by alexcrichton** [comment]
Oh `(core func $main "main")` is text-syntax sugar for an `(alias outer ...)` item. So for example this input:

```wasm
(component
    (core module $m
      (func (export "main") (result i32)
        i32.const 6
        i32.const 6
        i32.mul)
    )
    (core instance $main (instantiate $m))
    (func $main (result s32) (canon lift (core func $main "main")))
    (export "main" (func $main))
)
```

which uses the `(core func $main "main")` sugar will "elaborate to" (which you can see with `wasm-tools print`):

```wasm
(component
  (core module $m (;0;)
    (type (;0;) (func (result i32)))
    (func (;0;) (type 0) (result i32)
      i32.const 6
      i32.const 6
      i32.mul
    )
    (export "main" (func 0))
  )
  (core instance $main (;0;) (instantiate $m))
  (type (;0;) (func (result s32)))
  (alias core export $main "main" (core func (;0;)))
  (func $main (;0;) (type 0) (canon lift (core func 0)))
  (export (;1;) "main" (func $main))
)
```

note the `(alias core export $main "main" (core func (;0;)))` which popped up. The `wasm-encoder` crate should then have everything necessary to encode aliases as well.

**Comment by stephanos** [comment]
Fantastic! Thank you, that works!
