### ISSUE TITLE
wast: Parsing giant wat takes too much memory resources

### ISSUE THREAD

**Issue by Xyah3PBeHB** [bytecodealliance/wasm-tools#1095]
I have a giant wat (`385,794,195 bytes`) with `127384` functions (568 of which are imported functions) and I used `heaptrack` to analyze the memory usage when converting that wat to wasm using `wasm-tool` and `wat2wasm` (from wabt).

# wasm-tool

`heaptrack target/release/wasm-tools parse test.wat -o test1.wasm`

```
total runtime: 37.60s.
calls to allocation functions: 20932994 (556743/s)
temporary memory allocations: 8617065 (229183/s)
peak heap memory consumption: 6.20G
peak RSS (including heaptrack overhead): 6.06G
total memory leaked: 352B
```

# wat2wasm

`heaptrack wabt-1.0.33/bin/wat2wasm test.wat -o test2.wasm --enable-annotations`

```
total runtime: 31.10s.
calls to allocation functions: 23266595 (748122/s)
temporary memory allocations: 1561856 (50220/s)
peak heap memory consumption: 2.83G
peak RSS (including heaptrack overhead): 3.01G
total memory leaked: 0B
```

To my surprise the memory peak of wasm-tool was more than double that of wat2wasm. This is [wat](https://github.com/bytecodealliance/wasm-tools/files/11929997/sample.wat.gz) for testing.

**Comment by alexcrichton** [comment]
Thanks for the report! I've been digging in a bit and there's quite a bit of fruit to pick in this regard, so I'll try to make some PRs in the future to reduce the overhead here.

If I may be so bold as to ask, I'm curious if this caused issues for you somewhere? Or basically was curious what led to the motivation to make a comparison?

**Comment by Xyah3PBeHB** [comment]
First of all, thank you for optimizing the memory usage. I'd be happy to share the origin of this issue.
In the past I have used `wat2wasm` to analyze wasm. Recently, I plan to use `wasmparser` to automate some operations. First of all, I want to try the `wasm-tools` tool set. But in the behavior that I have been able to complete normally in the past (converting giant wat back to wasm), it ran out of memory (my device has not been upgraded for many years and only has 16G memory). So I want to compare it with the tools I used in the past.

**Comment by alexcrichton** [comment]
Makes sense and thanks for the context!

**Comment by alexcrichton** [comment]
Ok after https://github.com/bytecodealliance/wasm-tools/pull/1110 I think we're in a much better state now. Runtime still isn't fantastic but 2G is much better than the previous 6G. More improvements are still possible, but is that suitable for your use case? If so I'll probably go ahead and close this, but if not there's a thing or two that may be possible to optimize this further.

**Comment by Xyah3PBeHB** [comment]
Thank you very much for your efforts. I made a comparison based on the latest commit. Now not only is the memory peak lower than `wat2wasm`, but the performance has also been greatly improved and is far ahead. This has greatly exceeded the optimization potential I expected, and it is enough to use it on my old device.

# wasm-tool

`heaptrack target/release/wasm-tools parse sample.wat -o test1.wasm`

```
total runtime: 11.11s.
calls to allocation functions: 4072605 (366538/s)
temporary memory allocations: 1748744 (157388/s)
peak heap memory consumption: 2.04G
peak RSS (including heaptrack overhead): 2.01G
total memory leaked: 368B
```

# wat2wasm

`heaptrack wabt-1.0.33/bin/wat2wasm sample.wat -o test2.wasm`

```
total runtime: 25.57s.
calls to allocation functions: 23266595 (910024/s)
temporary memory allocations: 1561856 (61088/s)
peak heap memory consumption: 2.83G
peak RSS (including heaptrack overhead): 3.02G
total memory leaked: 0B
```
