### ISSUE TITLE
wit-parser: todo!() in Generator::call for option<resource>

### ISSUE THREAD

**Issue by cpetig** [bytecodealliance/wasm-tools#1120]
In function `abi::Generator::read_from_memory` the branch `TypeDefKind::Handle(_)` is unimplemented yet.

This can be triggered in wit-bindgen (C code, with Joel's resource patches) by a function returning 
an `option<resource>` or `result<resource, err>`.

[problem.zip](https://github.com/bytecodealliance/wasm-tools/files/12036976/problem.zip)

Related to https://github.com/bytecodealliance/wit-bindgen/pull/604

**Comment by alexcrichton** [comment]
Thanks! This is one of those pieces expected to be filled in as support grows, and it's currently known that the resources work in the bindgen area is not complete.

**Comment by cpetig** [comment]
I don't trust below solution to be fully correct yet, but 
```
self.stack.push(addr);
self.load_intrepr(offset, Int::U32);
self.lift(ty);
```
seems generate the correct code in the example I checked.

**Comment by cpetig** [comment]
I found a more simple way to express this (by using I32Load instead of calling load_intrepr).
