### ISSUE TITLE
Component encoding GC not detecting dead type imports

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/wasm-tools#1139]
I've attached a component which has `wasi:filesystem/filesystem` fully virtualized.

This component still contains an unnecessary `wasi:filesystem/filesystem` import though for filesystem types that are unused.

Explicitly deleting these type imports the component still validates, which points to this being a bug in the component encoder GC for unused type imports.

Attached is the replication core Wasm with embedded component resolution. Just let me know if there's any further info I can provide on this case.

[tmp.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/12148755/tmp.wasm.gz)

**Comment by alexcrichton** [comment]
Thanks for the report! Should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1143
