### ISSUE TITLE
Yet another valid wasm module does not validate: `select` and `if` in unreachable code

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasm-tools#115]
Originally discovered in https://github.com/fitzgen/wasm-smith/pull/21

We have a `select` and an `if` in unreachable code. I've annotated each line with the stack after the instruction is executed below:

```wasm
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    i32.const -393040     ;; [i32]
    i32.const -9211021    ;; [i32 i32]
    i32.const -1          ;; [i32 i32 i32]
    br 0 (;@0;)           ;; [i32 i32 i32]
    select                ;; [i32]
    if  ;; label = @1     ;; []
    end))                 ;; []
```

[test.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/5379680/test.wasm.gz)

### Reproduce

```
$ cargo run --bin wasm-validate-rs -- test.wasm
```

### Expected

It validates okay.

### Actual

```
Error: type mismatch: stack size does not match block type (at offset 80)
```

**Comment by fitzgen** [comment]
FWIW: both WABT and Binaryen report `test.wasm` is valid.

**Comment by alexcrichton** [comment]
Hm this seems to validate for me on 890f374cbc50b2647b7ac95682e10288fb70db9f, do you perhaps have an older checkout?

**Comment by fitzgen** [comment]
Perhaps I do, and perhaps `wasm-smith` is also using an older `wasmparser`.

**Comment by fitzgen** [comment]
Fixed in https://github.com/fitzgen/wasm-smith/pull/22
