### ISSUE TITLE
`Local` struct do not implement `Parse` trait

### ISSUE THREAD

**Issue by anoopelias** [bytecodealliance/wasm-tools#1156]
Regarding [`Local<'a>` struct](https://github.com/bytecodealliance/wasm-tools/blob/559ede0a436240cb7dfe162c568f398655e9b18c/crates/wast/src/core/func.rs#L85) in `crates/wast`, Is there a reason why this struct do not implement `Parse<'a>`?

The alternative, [`parse_remainder`](https://github.com/bytecodealliance/wasm-tools/blob/559ede0a436240cb7dfe162c568f398655e9b18c/crates/wast/src/core/func.rs#L96) is not visible outside the crate. This is preventing me from parsing `local` outside of a `func`.

I can work around this for the time being, but I am curious if there is a reason to do it this way. Thanks.

**Comment by alexcrichton** [comment]
No particular reason, it's just how things are structured. Should be fine to refactor and add this!

**Comment by anoopelias** [comment]
This is what I figured:

An instruction like `(local i32 i32)` is a valid one, just that it generates multiple "local"s (Like `Local { None, None, i32 }` twice). Hence it is not possible to implement trait `Parse` for struct `Local`.

Still I feel it is useful extracting something like a `LocalParser` that can generate multiple "local"s as shown in the [referenced commit](https://github.com/anoopelias/wasm-tools/blob/0b494c84a78af306497d6fce961836ef4abc68b4/crates/wast/src/core/func.rs#L103). This way we still can parse `local` outside of a`func`.

Let me know what you think. Happy to raise a PR if you think this can be accepted.

**Comment by alexcrichton** [comment]
Sure yeah, I think it's reasonable to expose a parser in one way or another
