### ISSUE TITLE
Future of old syntax for `local.get` or `global.set`

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasm-tools#1164]
Currently, two versions of syntax for some instructions exist, e.g.`local.get` and `get_local`. Is there a plan to phase out the latter version?

See also https://github.com/WebAssembly/spec/issues/884

**Comment by alexcrichton** [comment]
I don't believe any plans exist yet to phase out the old syntax, but it hasn't been the primary syntax in so long I think it'd be fine to delete all the old syntax at any time now. Would you be up for sending a PR to delete the old syntax?
