### ISSUE TITLE
Compose direct cyclic component dependencies

### ISSUE THREAD

**Issue by juntyr** [bytecodealliance/wasm-tools#1165]
At the moment, component dependencies must be entirely acyclic. However, additional functionality could be enabled by allowing wasm-compose to resolve a direct cyclic dependency pair such as B <-> C:

* A depends on B
* (B depends on C, C depends on B)
* C depends on D

to transform it into:

* A depends on BC
* BC depends on D

Would something like this ever be possible or is it entirely incompatible with the component model?

**Comment by alexcrichton** [comment]
I think that the way this would look is that the "BC" in your above example would be a single component that itself perhaps shares memory with core wasm modules (or not, either way). I'm not aware of any means myself to go from a component B and a compnent C that cyclicly depend on each other to a "BC" which works.

**Comment by juntyr** [comment]
Ok, thanks for your insight!
