### ISSUE TITLE
wasm-tools: implementation of imports naming implementations (component-model #222)

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasm-tools#1198]
https://github.com/WebAssembly/component-model/pull/222

**Comment by pchickey** [comment]
We will ship compatibility with this change in wasmtime 15.

We can add support to tooling today to support the old mode and new mode, and at some point we will deprecate support for the old mode.

**Comment by alexcrichton** [comment]
This is now done and implemented, so closing.
