### ISSUE TITLE
wit-component: support resource exports from adapters

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/wasm-tools#1200]
#1084 added support for resources to `wit-component`, but appears to only support exporting resources from the main module -- not from adapters.  Given that `wasm-tools component link` represents all dynamic libraries as "adapters", and `componentize-py` uses that to create components, I'd like to add support for exporting resources from adapters.

I'm planning to start working on a PR tomorrow unless there are objections.

**Comment by alexcrichton** [comment]
Sounds good to me 👍

**Comment by dicej** [comment]
Just a quick update: I've implemented this, but I'm still adding tests to `componentize-py` to exercise it in all the ways I can think of.  Once that's done and once I've added a test or two to `wit-component` itself, I'll open a PR.
