### ISSUE TITLE
wit: Change syntax to require semicolon delimiters

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasm-tools#1205]

**Comment by alexcrichton** [comment]
IIRC we talked at one point about updating WIT syntax to require semicolons and IIRC it had to do with IDE auto-complete/highlighting or similar. I dont' recall the discussion going too too far though and I've never dug into this much myself.

Out of curiosity though what prompted this?

**Comment by alexcrichton** [comment]
@lukewagner or @elliottt do y'all recall the context around this? And/or do y'all think we should add semicolon termination to some statements in WIT?

**Comment by lukewagner** [comment]
The context is just taking a moment, before things are relatively harder to change post-Preview-2, to consider [component-model/#142](https://github.com/WebAssembly/component-model/issues/142).  I don't have a super strong opinion on this; just a vague fear that lack of semicolons now will paint us into a corner in the future as we expand WIT (or force us to do some sort of Automatic Semicolon Insertion-like hack).

**Comment by elliottt** [comment]
I think the context was that while working on a wit file I accidentally terminated something with `;`. I suggested offhand that maybe the comment character should have been `;`, and then we wondered if it was worth discussing semicolons a bit before finalizing things.

**Comment by alexcrichton** [comment]
Ah yes thank you for the link, that's what I was remembering! I still think that's all reasonable to add, so I'll work on this.

**Comment by alexcrichton** [comment]
I've drafted a spec (aka I threw a bunch of semicolons at the wall) at https://github.com/WebAssembly/component-model/pull/249 and also outlined a plan for implementing this without hopefully too much churn headache.

**Comment by alexcrichton** [comment]
cc https://github.com/bytecodealliance/wasm-tools/pull/1212

**Comment by alexcrichton** [comment]
[Started a zulip chat on this](https://bytecodealliance.zulipchat.com/#narrow/stream/223391-wasm/topic/WIT.20and.20semicolons) for broader visibility

**Comment by pchickey** [comment]
This is progressing well - the rollout strategy is underway. The default will be switched to require semicolons in early November for wasmtime 15, and the support for not requiring semicolons will be removed in december (wasmtime 16)
