### ISSUE TITLE
wast: does not support recently added atypical condition test

### ISSUE THREAD

**Issue by ia0** [bytecodealliance/wasm-tools#1213]
Parsing the `if.wast` file of the WebAssembly/spec test suite fails after https://github.com/WebAssembly/spec/pull/1682.

https://github.com/WebAssembly/spec/blob/bfb21e96f99820e0cfb0c41a264bd0d42795bfe2/test/core/if.wast#L530-L534
```wast
  (func (export "atypical-condition")
    i32.const 0
    (if (then) (else))
    (if (i32.const 1) (i32.eqz) (then) (else))  ; it fails on the "then"
  )
```

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1215
