### ISSUE TITLE
Does wasm-smith consider the semantics between instructions when generating instructions.

### ISSUE THREAD

**Issue by abc767234318** [bytecodealliance/wasm-tools#1278]
I have generated a wasm binary using wasm-smith. And I found an interesting piece of instructions shown as follows:
<img width="459" alt="image" src="https://github.com/bytecodealliance/wasm-tools/assets/51507451/17f65949-a32c-4d7d-865f-8dd2ad1b8b1b">
The instructions after the `br 1` are impossible to be executed. So, does wasm-smith generate instructions purely with stack balance as a priority and not much with semantics?

**Comment by alexcrichton** [comment]
Yes wasm-smith knows that code after `br 1` is unreachable. The code afterwards is mostly to test validators as opposed to runtimes to ensure that the module is still considered valid. Does that answer your question here?

**Comment by abc767234318** [comment]
Thank you very much for your clear answer
