### ISSUE TITLE
wasm-parser: provide configuration for limits

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [bytecodealliance/wasm-tools#1280]
This is currently hardcoded
https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasmparser/src/limits.rs

**Comment by fitzgen** [comment]
These limits match the generally agreed upon implementation limits enforced by basically all wasm engines, and aren't something that we will make configurable.

https://webassembly.github.io/spec/js-api/index.html#limits
