### ISSUE TITLE
wit-component example is broken

### ISSUE THREAD

**Issue by iamshreeram** [bytecodealliance/wasm-tools#1300]
The example in [usage](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wit-component/README.md#usage) section of `wit-component` contains `demo.wit` 
```
interface host {
  hello: func()
}
default world demo {
  import host: self.host
}
```
This is throwing below error - 
```
error: expected ';', found '}'
```

Looks like, below is the valid `demo.wit` that gets compiled to component. 
```
package hello:local;

interface host {
  hello: func();
}
```

Did the linting or syntax change w.r.t `wasm-tools`?

**Comment by pchickey** [comment]
Yes, the syntax has changed - wasm-tools now requires semicolons terminators, which were previously optional. If you need to override this temporarily, you can set environment variable `WIT_REQUIRE_SEMICOLONS=0`. The use of that environment variable will go away in a release in the next month or so, and semicolons will be required unconditionally.
