### ISSUE TITLE
Smith generates wasm files with elem.drop even with bulk memory disabled

### ISSUE THREAD

**Issue by kripken** [bytecodealliance/wasm-tools#1324]
`elem.drop` is part of [bulk memory](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md#instruction-encoding), but it is emitted by this command:

```
$ wasm-tools smith input.dat -t -o /dev/stdout --bulk-memory false | grep elem.drop
      elem.drop 1
      elem.drop 1
        elem.drop 2
      elem.drop 2
            elem.drop 2

```

Tested on latest release, `wasm-tools-1.0.54-x86_64-linux/`.

[input.dat.gz](https://github.com/bytecodealliance/wasm-tools/files/13622209/input.dat.gz)

**Comment by alexcrichton** [comment]
Thanks for the report! Should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1326
