### ISSUE TITLE
Error when running `component new` for a `wasm32-wasi` target binary

### ISSUE THREAD

**Issue by landonxjames** [bytecodealliance/wasm-tools#1352]
I have this wit file:
```wit
package wasm-version-tests:component;

interface clients { 
  resource wasm-version-tests-client {
    constructor();
    hello-world: func() -> string;
  }
}


world wasm-version-tests { 
  export clients;
}

```

Implemented by this Rust code:
```rs
wit_bindgen::generate!({
world: "wasm-version-tests",
exports: {
    "wasm-version-tests:component/clients/wasm-version-tests-client": WasmVersionTestsClients,
},
use exports::wasm_version_tests::component::clients::GuestWasmVersionTestsClient;

pub struct WasmVersionTestsClients;

impl GuestWasmVersionTestsClient for WasmVersionTestsClients {
    fn hello_world(&self) -> String {
        println!("TESTING STDOUT");
        return "Hello World".to_string();
    }

    fn new() -> Self {
        WasmVersionTestsClients
    }
}
```

When I compile this to `wasm32-unknown-unknown` and then run `wasm-tools component new` on the resulting `.wasm` file everything works as expected. When I compile it to `wasm32-wasi` (to make use of printing to std out, etc) I get an error from `wasm-tools component new`:
```sh
> cargo build --target=wasm32-wasi --release --manifest-path ./runtime/Cargo.toml

   Compiling wasm_version_tests v0.0.1 (/Volumes/workplace/wasmVersionTests/runtime)
    Finished release [optimized] target(s) in 0.37s

> wasmVersionTests@0.0.1 build:wasm-component
> wasm-tools component new ./runtime/target/wasm32-wasi/release/wasm_version_tests.wasm -o ./runtime/target/wasm32-wasi/release/wasm_version_tests_component.wasm

error: failed to encode a component from module

Caused by:
    0: module requires an import interface named `wasi_snapshot_preview1`
```

I am not sure how to add in the import interface for `wasi_snapshot_preview1`, I was under the impression that Rust's `wasm32-wasi` target supported that by default. Is this similar to the `wit` definitions for `wasi_snapshot_preview2` that need to be added to a `wit/dep/` directory? Just looking for some guidance on building WASI based components (and will hopefully contribute a more explanatory error when I get this all figured out)

**Comment by pchickey** [comment]
This is a different error than your wit-bindgen deps error. The error message isn't great, but what `component new` is reporting is that your module has imports in the `wasi_snapshot_preview1` namespace, which it cannot satisfy with component imports. Your module imports from `wasi_shapshot_preview1` to implement parts of the `std` library when built for the `wasm32-wasi` target. Those same parts of `std` do nothing, or trap, when you use them under `wasm32-unknown-unknown`.

To resolve this error, you need to pass an `--adapt `wasi_snapshot_preview1.reactor.wasm` where that file is one you download from https://github.com/bytecodealliance/wasmtime/releases/tag/v16.0.0, or matching the release of wasmtime you are using.

**Comment by alexcrichton** [comment]
I believe this question was solved, so I'm going to close this
