### ISSUE TITLE
`wasmparser`: validation rejects ref.cast  

### ISSUE THREAD

**Issue by skuzmich** [bytecodealliance/wasm-tools#1354]
This module validates in both spec interpreter and V8:
```
;; test.wat
(module 
  (type $a (array (mut i16)))
  (func 
    i32.const 0
    array.new_default $a
    ref.cast (ref null $a)
    drop
  )
)
```

Current [main](https://github.com/bytecodealliance/wasm-tools/commit/4d1f5031027e46b322cc0c9ac8234ad42756c249) branch of wasm-tools rejects it:
```
$ wasm-tools validate -f gc test.wat  
error: func 0 failed to validate

Caused by:
    0: ref.cast's heap type must be a sub type of the type on the stack: (ref null (id 0)) is not a sub type of (ref any) (at offset 0x1f)
```

This issue prevents validation of wasm modules produced by Kotlin in debug builds. In production builds, binaryen removes these useless casts, allowing validation to succeed.

**Comment by alexcrichton** [comment]
GC should now be fully implemented, so closing.
