### ISSUE TITLE
wast: incorrect parse in testsuite comments.wat

### ISSUE THREAD

**Issue by osa1** [bytecodealliance/wasm-tools#1368]
Simpler version of the [failing test][1]:

```wat
(module quote
  "(func (export \"f2\") (result i32)"
  "  (i32.const 1)"
  "  ;; comment\0d"
  "  (return (i32.const 2))"
  "\0a"
  ")"
)

(assert_return (invoke "f2") (i32.const 2))
```

The `QuoteModule` for this function is missing one of the `i32.const`s:

```
[crates/spec-test/src/spec.rs:240] &module = [
    ...
    10, // code section
    6,  // size = 6
    1,  // number of entries = 1
    4,  // size = 4
    0,  // 0 locals
    65, // i32.const
    1,  // 1
    11, // end
]
```

In the full test there are three copies of this function with comments in different places. The other two are parsed as expected.

[1]: https://github.com/WebAssembly/testsuite/blob/dc27dad3e34e466bdbfea32fe3c73f5e31f88560/comments.wast#L83-L106

**Comment by alexcrichton** [comment]
Thanks for the report! I think this should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1372
