### ISSUE TITLE
Add shell completion script generation to the CLI

### ISSUE THREAD

**Issue by mainrs** [bytecodealliance/wasm-tools#1371]
`clap` provides a package for this called available at https://crates.io/crates/clap_complete.

The package would be added as a runtime dependency. The CLI could then provide a new command called `completion`, accepting the shell name and printing the completion script to stdout.

If this feature is desired, I can open a PR.

**Comment by alexcrichton** [comment]
Seems reasonable to me to add! If you're up for sending a PR I'm happy to give it a review
