### ISSUE TITLE
Question: TypeDef owner is None for anonymous types

### ISSUE THREAD

**Issue by yowl** [bytecodealliance/wasm-tools#1376]
Hi, for anonymous types, i.e. in `TypeDef` `name` is `none`, the `owner` is also `none` when the type appears in an interface e.g.

```
interface x{
record o-one {
  a: option<bool>
}
}
```
The `option<bool>` type has no owner, event though it could in theory be the interface I think, is there a reason for this?

**Comment by alexcrichton** [comment]
There's not a strong reason for this really. My hope was that the lack of owner would make it easier to deduplicate these types but I don't think that's manifested anywhere yet. I think it'd be reasonble to start setting the `owner` field here.

**Comment by yowl** [comment]
Thanks, that makes sense.  Currently I'm maintaining a map to the owner, and I can see how not having the owner could indicate a type could be deduplicated, but I guess the `name` could also serve that purpose.  I'll look at wit-parser to see what it involves.
