### ISSUE TITLE
wasm-smith depends on wasmparser by default again

### ISSUE THREAD

**Issue by eqrion** [bytecodealliance/wasm-tools#1383]
#1301 made wasmparser an optional dependency of wasm-smith, #1330 landed a bit later and seems to have inadvertently brought this back.

[Cargo.toml](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasm-smith/Cargo.toml#L27). The issue seems to be that while wasmparser is still optional for wasm-smith, wasm-smith by default enables the wasmparser feature for wasm-encoder.

@alexcrichton Do you know of a way to fix this? I'm pretty sure it's not our fault, we're not enabling anything odd when depending on wasm-smith.

**Comment by alexcrichton** [comment]
Oops sorry about that! I've fixed that in https://github.com/bytecodealliance/wasm-tools/pull/1384 and additionally added a CI check to make sure it doesn't come back. I'll publish once that's merged.

**Comment by eqrion** [comment]
Thanks!

**Comment by alexcrichton** [comment]
The version bump is at https://github.com/bytecodealliance/wasm-tools/pull/1385
