### ISSUE TITLE
Relax external MAX_WASM_MEMORIES check for imported memory count

### ISSUE THREAD

**Issue by chrisdickinson** [bytecodealliance/wasm-tools#1389]
Hi! I've been using `wasmencoder` by way of `componentize-py`. In particular, I've been using `componentize-py` to compile the native dependencies of a Python package to Wasm shared libraries – following along the pattern @dicej established with [`wasi-wheels`](https://github.com/dicej/wasi-wheels).

It's been pretty successful so far, but I ran into a snag: it looks like imported memories – such as the ones defined by Python `wasm32-wasi` "native" packages – count against [the validation](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasmparser/src/validator/component.rs#L2309-L2318) the encoder performs.

With the packages I've translated thus far, there are something like 81 memory imports; I believe `componentize-py` adds some more, pushing the resulting component across the `MAX_WASM_MEMORIES` check threshold. However, the component that `componentize-py` produces only contains a single core `(memory)`, shared many times. I found it surprising that these references would count against the maximum memory count. (However, it's possible I'm misunderstanding the purpose of the limit!)

**Comment by alexcrichton** [comment]
Yes I think this is definitely a bug in the validator where you probably don't have 81 linear memories but 81 aliases to the same linear memory. Do you have an example component you could share? I can reproduce this with:

```wasm
(component
  (core module $m
    (memory (export "m") 1)
  )
  (core instance $i (instantiate $m))
  (alias core export $i "m" (core memory))
  ;; ... repeat that 100 times ...
  (alias core export $i "m" (core memory))
)
```

But I'd also like to confirm with a concrete component you have which doesn't validate if possible too

**Comment by chrisdickinson** [comment]
Sure – here's [a link](https://github.com/chrisdickinson/component-sandbox-demo/blob/example-sandbox/sandbox.wasm) to a component containing a number of python native packages. I ran into the problem when I added `pandas` to the component; `componentize-py` fails to generate an output component due to the wasmencoder error:

```
Traceback (most recent call last):
  File "/Users/chris/projects/dylibso/li/demo/venv/bin/componentize-py", line 8, in <module>
    sys.exit(script())
             ^^^^^^^^
AssertionError: failed to validate component output

Caused by:
    memories count exceeds limit of 100 (at offset 0xebe202a)
```

(If you need the source to recreate the component, let me know – I've got kind of a mess of submodules set up for testing but can look into cleaning it up if that's helpful. 😅 )

**Comment by alexcrichton** [comment]
Ok thanks! I think https://github.com/bytecodealliance/wasm-tools/pull/1390 should fix that case then, and I can do a version bump once that's ready.
