### ISSUE TITLE
wasm-tools parse support for .wast file.

### ISSUE THREAD

**Issue by doehyunbaek** [bytecodealliance/wasm-tools#1395]
From current README, I got the impression that both wat and wast crates are accessible from subcommand parse:

https://github.com/bytecodealliance/wasm-tools/blob/d15fda33f309a27cd507d7739d7b5208575e9b78/README.md#L128

But as I try out the command from the shell and also looking through the code, this doesn't seem currently possible:

https://github.com/bytecodealliance/wasm-tools/blob/49753602683a539b66d0a65ffa11acb402f148bb/src/lib.rs#L67-L72

Is it intended? If not, may I contribute a feature addition?

**Comment by alexcrichton** [comment]
Ah yes so `*.wast` support isn't surfaced in the CLI at this time. The `wat` crate is itself built on the `wast` crate (it's a very small shim) and the `wast` crate has support for both the text syntax and the `*.wast` assertion syntax. (sorry if that's confusingly named)

I'd be happy to see `*.wast` support in the CLI, but I'm not entirely sure what that might look like. Do you have an idea in mind though of what `wasm-tools parse foo.wast` might do?

**Comment by doehyunbaek** [comment]
I did not have particular output format in mind, but I found that our team uses [wast2json](https://github.com/WebAssembly/wabt/blob/main/docs/wast2json.md) tool from wabt.

What do you think about implementing wast support as a drop-in replacement for wast2json? Pro would be that it would be really useful for the migration of the users.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! If you're up for making a PR that'd be most welcome as well, I'd be happy to review.

If I might throw out an initial idea to help shape this a bit:

* I can't think of a better name than `wasm-tools wast2json` myself
* Perhaps the output is JSON to stdout by default, `-o` outputs the JSON to a file, and `--module-dir` is a required argument of where to put all the modules?
* I'd recommend using `serde_json` and `serde::{Deserialize,Serialize}` for JSON things in Rust
* I'd prefer to keep the serde bits out of `wast` if possible (keeps its dependencies slim), so what I'd recommend is a `src/bin/wasm-tools/wast2json.rs` which has all the serde bits. That'd use [`Wast`](https://docs.rs/wast/latest/wast/struct.Wast.html) to convert to a structure which has `#[derive(Serialize)]` and then it could all be emitted as JSON.

Please feel free of course to change any details as well, just some initial suggestions!

**Comment by doehyunbaek** [comment]
I'll try to follow up with a PR with respect to your suggestion. Thanks!

**Comment by doehyunbaek** [comment]
Oh @alexcrichton thanks for implementing this. I thought about doing thsis early April because I have some important due date in a few weeks. Maybe I should have communicated it.

Again thanks for your help!

**Comment by alexcrichton** [comment]
Oh I'm so sorry! I was feeling inspired the other night, but I also should have checked in here first before going ahead.

**Comment by doehyunbaek** [comment]
No I am really grateful that you did it! No need to be sorry!
