### ISSUE TITLE
wasm-encoder: support extended constant expressions

### ISSUE THREAD

**Issue by ThePuzzlemaker** [bytecodealliance/wasm-tools#1397]
I've noticed that #687 added the groundwork for implementing the extended constant expressions proposal, but `wasm-encoder` still does not support them. Are there any plans for this, and if so, when can I expect them to be available? This isn't a pressing issue for me, hence why I don't open a PR at this point, but I wanted to check in on this.

**Comment by fitzgen** [comment]
As far as I know, no one has plans to implement extended const expressions for `wasm-encoder` at this time. I'm sure it will happen *eventually*, but that could easily be in another year or so.

If you want it badly enough to implement it, I'm happy to point you to the relevant parts of the crate, answer questions, and review PRs.

**Comment by ThePuzzlemaker** [comment]
I presume the solution would just to add some functions which encode the relevant instructions to `ConstExpr`. Would the functions just look as such?
```rs
impl ConstExpr {
    fn i32_add(self) -> Self { /* ... */ }
}
```

**Comment by ThePuzzlemaker** [comment]
Hmm, avoiding breaking changes would be difficult: the current `i32_const` & co. functions have the signature
```rs
fn i32_const(value: i32) -> Self;
```
But in order to have multiple `i32.const`s (e.g. in a `(i32.add (i32.const 0) (i32.const 1))` const expr, which is allowed by this proposal), it must have the signature:
```rs
fn i32_const(self, value: i32) -> Self;
```
Should I make this breaking change, or simply add `with_i32_const(self, value: i32) -> Self` functions? (bikeshed: naming)
