### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jpages** [bytecodealliance/wasm-tools#1401]
Hello,

Could we get a new release soon? I would like to use https://github.com/bytecodealliance/wasm-tools/pull/1394 in SpiderMonkey.

Thanks!

**Comment by pchickey** [comment]
@alexcrichton usually does these releases and is at an offsite this week, so he may be slower to respond than usual.

**Comment by alexcrichton** [comment]
I've posted a bump at https://github.com/bytecodealliance/wasm-tools/pull/1406
