### ISSUE TITLE
feature request: pack executable files

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/wasm-tools#1430]
Is it possible to add a `pack` command to package a wasm(with component model) file into an executable file?

Allow users who do not have the wasm runtime installed to run it directly.

**Comment by alexcrichton** [comment]
Thanks for the report, but this is something I can say with relative certainty is outside the purview of this crate. Making a wasm file executable requires choosing a runtime and everything runtime-related is outside of the scope of this tool. This repository is about working with wasm files and operating on them as oppose to executing them. I'd recommend opening this issue on the runtime of your choice, however, as this would be a good feature request for that.
