### ISSUE TITLE
wast: Make `V128Const`, `V128Pattern` and `NanPattern` clonable

### ISSUE THREAD

**Issue by ohorn** [bytecodealliance/wasm-tools#1444]
In some use cases it would be helpful if the enums `V128Const`, `V128Pattern` and `NanPattern` would derive (or otherwise implement) the `Clone` trait?

Or is there a particular reason against it?

**Comment by alexcrichton** [comment]
No problem adding these, should be fine to do! Would you be interested in sending a PR for this?

**Comment by ohorn** [comment]
Sure, I will open a PR.
