### ISSUE TITLE
Support for inserting instructions in expression instrs: wast crate

### ISSUE THREAD

**Issue by N0il** [bytecodealliance/wasm-tools#1448]
I have been trying insert instructions dynamically to the array of instructions of a function, but as the Instruction enum does not implement clone, I am not being able to do it, is there any way of doing this?

**Comment by alexcrichton** [comment]
I think it'd be reasonable to implement `Clone` for instructions, if you're up for it a PR would be most welcome!

**Comment by N0il** [comment]
Sorry for taking so long answering, I agree and I am up to do it, as I am relatively new to rust can you guide me please? @alexcrichton

**Comment by alexcrichton** [comment]
I believe you'd start by adding `Clone` [here](https://github.com/bytecodealliance/wasm-tools/blob/c85632b22db1fd7a6b9b7146fc1df204e19d5afb/crates/wast/src/core/expr.rs#L352) and then playing whack-a-mole with compiler error messages to add `Clone` to more things too

**Comment by N0il** [comment]
> I believe you'd start by adding `Clone` [here](https://github.com/bytecodealliance/wasm-tools/blob/c85632b22db1fd7a6b9b7146fc1df204e19d5afb/crates/wast/src/core/expr.rs#L352) and then playing whack-a-mole with compiler error messages to add `Clone` to more things too

Ok I will, thank you 🙂
