### ISSUE TITLE
Consider publishing wasmparser-dump

### ISSUE THREAD

**Issue by olivierlemasle** [bytecodealliance/wasm-tools#146]
Hi,

I'm currently in the process of packaging `wat` and `wast` crates for Fedora (as rpm packages). In order to execute the tests during build, the dev-dependencies of these crates should be published on crates.io.

Would you consider publishing `wasmparser-dump` (and, if possible, adding the `version` identifier to dev-dependencies in all crates)?

**Comment by alexcrichton** [comment]
For now the dump crate is intended to be internal (it's at least something I don't want to maintain on crates.io). I'm not sure how packaging works though so I'm not sure if there's something else that would work for you

**Comment by olivierlemasle** [comment]
@alexcrichton Thank you for your reply.
Actually, I've just found that `wasmparser-dump` is not needed to run `wasmparser` tests (BTW, why is it listed in `wasmparser`'s dev-dependencies?), so I'll be able to build and test `wat`, `wast` and `wasmparser` and package them in Fedora.
