### ISSUE TITLE
New crate: `wit-encoder`

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/wasm-tools#1504]
Right now there is no structured way to build WIT files. The only code we have is in `wit-smith`, but that is built specifically for automated testing.

I'm currently looking at generating WIT for [`wasm-http-tools`](https://github.com/yoshuawuyts/wasm-http-tools) from OpenAPI definitions. And I know @MendyBerger has recently worked on something similar for WebIDL too. It would be great if we could all share wit codegen as part of `wasm-tools`.

I spoke to @alexcrichton about this a few weeks ago, and he agreed to this in principle. Mendy and I spoke about this too, and either of us would be happy to contribute this work. I mostly wanted to make sure we also had a record of our conversations here before filing any kind of PR. Thanks!

**Comment by yoshuawuyts** [comment]
Actually, I might just try and knock this one out today. I'm keen on a little coding project. Feel free to assign this to me (if that's possible!)

**Comment by yoshuawuyts** [comment]
Oh actually, to answer my own question here: `wit_parser::Package` doesn't actually contain interfaces or worlds directly - it contains names and IDs which can be looked up in shared table. Yeah, we probably should write a dedicated encoder crate instead.

**Comment by alexcrichton** [comment]
Oh if `Display`/printing is what's desired there's also [`WitPrinter`](https://docs.rs/wit-component/latest/wit_component/struct.WitPrinter.html) which will serialize a `Resolve`'s package to a string which might be what you want here?

**Comment by MendyBerger** [comment]
(can't believe I didn't see WitPrinter before, would've saved me hours!)
