### ISSUE TITLE
Issue in looking up event indices in `throw` instruction validation

### ISSUE THREAD

**Issue by takikawa** [bytecodealliance/wasm-tools#153]
I think there is a small bug in validating `throw` in cases like the following:

```
(assert_invalid
  (module
    (type (func))     ;; func type at index 0
    (func throw 0))   ;; event at index 0, which is missing
  "throw index out of bounds")
```

I believe this should be invalid, because the `throw` argument index should index into the events vector of the module, but it's looking up in the function types vector instead. Currently it doesn't throw an error.

(I can submit a PR to fix this, though maybe I should wait to see if there are thoughts on PR #152 first as it affects `catch` in that PR too)

**Comment by yurydelendik** [comment]
> I believe this should be invalid, because the throw argument index should index into the events vector of the module

Yes, we need to fail here.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/bytecodealliance/wasm-tools/pull/154
