### ISSUE TITLE
Export conflicts

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytecodealliance/wasm-tools#1538]
Hi All,

When two components export the same symbols, and they are composed to have a single component, then there will be a conflict of symbols. How does the Wasm compose tool resolve/address this? Because the composed component must export all the export calls from both the components. Please help me how to resolve this issue.

Thanks & Regards,
Pradeep

**Comment by alexcrichton** [comment]
The wasm-compose crate I think may not handle this super well without extra configuration, but nowadays it's recommended to use [wac](https://github.com/bytecodealliance/wac) instead for composition which has better utilities for handling cases like this. Does that work for you?

**Comment by PradeepKiruvale** [comment]
@alexcrichton thanks for the reply, sure that works. Do you mean that the WAC already supports this kind (Same symbol) of a component composition? Please share if there are any examples, that will be very useful.

**Comment by PradeepKiruvale** [comment]
Thank you, I will have a look at it.
