### ISSUE TITLE
obsolete comment for `push`

### ISSUE THREAD

**Issue by FrankReh** [bytecodealliance/wasm-tools#1559]
The part of the comment describing the `deps` argument is wrong now that the function signature has changed and there is no longer a `deps` argument.

I didn't want to just remove the line in a PR, hoping a maintainer would have a newer rewrite for the whole function doc string, as the act of pushing an unresolved package is such a pivotal  part of building a complete set of resolved WIT packages. There may be nuances that the function signature cannot capture.

https://github.com/bytecodealliance/wasm-tools/blob/c6732bb781f1d5bcb51bf1f175a5fdd623c3652e/crates/wit-parser/src/resolve.rs#L339-L340

**Comment by alexcrichton** [comment]
Thanks for the report! I've updated the comment in https://github.com/bytecodealliance/wasm-tools/pull/1561
