### ISSUE TITLE
Extract wit from wasm file

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/wasm-tools#1560]
I want to extract the wit file from the wasm file compiled from the component model. 

Is there such an interface now?

**Comment by rylev** [comment]
You can use `wasm-tools component wit --out-dir wit mycomponent.wasm` which will output the entire wit package and any dependencies to the directory specified with `--out-dir`.

**Comment by oovm** [comment]
I'm actually developing a command line tool
Should I copy the code from here: https://github.com/bytecodealliance/wasm-tools/blob/c6732bb781f1d5bcb51bf1f175a5fdd623c3652e/src/bin/wasm-tools/component.rs#L568

**Comment by rylev** [comment]
I think that might be best. You could also try moving some of that logic into `wit-component` and then you wouldn't have to copy paste as much, but I'm nto super familiar with that part of the code base.

**Comment by oovm** [comment]
It's up to you, I don't really need to follow the `deps/` directory convention.
I'm going to follow the [inline proposal](https://github.com/WebAssembly/component-model/issues/313) and put multiple packages in the same wit file, so I need to make some changes to this code.

**Comment by alexcrichton** [comment]
Yes please feel free to copy that! Once that proposal is implemented here as well I think it'll make sense to change `wasm-tools component wit` to that output by default as well.
