### ISSUE TITLE
`Stability` set to `Unknown` intially and triggering assert on non-empty value coming in

### ISSUE THREAD

**Issue by vados-cosmonic** [bytecodealliance/wasm-tools#1666]
In attempting to implement `@since` and related feature gates in `jco` I ran into an issue that may be long here. 

First, all the `Stability` values in functions on the `Resolve` *seem* to be `Unknown`.

Secondly, it seems that there's a panic when running `wit-bindgen` on newer WITs with `@since` annotations in them -- in particular the code that panics is the following:

https://github.com/bytecodealliance/wasm-tools/blob/v1.212.0/crates/wit-parser/src/resolve.rs#L2350

I'm not sure exactly why but there is *already* a value of `Unknown` in place and when the new value (correct seeming) value comes along, the previous one existing triggers the assertion.

Assuming this case really *shouldn't* be happening (if the idea is that once the stability is encountered it should never change), it seems that at the very least a more complete error message (perhaps a `bail` rather than the `assert_eq` there) should be used at the very least

@cpetig ran into the panic due to that `assert_eq`:

```
thread 'main' panicked at …/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-parser-0.212.0/src/resolve.rs:2350:21:
assertion `left == right` failed
  left: Interface { id: Id { idx: 1 }, stability: Unknown }
 right: Interface { id: Id { idx: 1 }, stability: Stable { since: Version { major: 0, minor: 2, patch: 0 }, feature: None } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With a pretty basic WIT-only project with the following `deps.toml`:

```toml
cli = "https://github.com/WebAssembly/wasi-cli/archive/main.tar.gz"
clocks = "https://github.com/WebAssembly/wasi-clocks/archive/main.tar.gz"
```

(i.e. you could reproduce it with a folder named `wit` with only that `deps.toml` and a call to `wit-deps` then a recent version of `wit-bindgen`

**Comment by alexcrichton** [comment]
Thanks for the report! Definitely agreed this shouldn't be a panic. The issue I think is that in wasi-clocks itself it's using `@since` but in wasi-cli it's not. That discrepancy leads to this panic where the panic was designed for before stability annotations and now it's surfacing this discrepancy. I'll work on fixing this.

**Comment by vados-cosmonic** [comment]
Ahhh -- thanks @alexcrichton , this makes sense -- @cpetig noted something along the same lines IIRC, thinking that the problem was with `wasi-cli` in particular.

So if I'm understanding right, basically the WIT for `wasi-cli` got pulled in *before* the WIT for `wasi-clocks` (which lexicographically makes sense anyway, though not sure if it's ordered that way)?

**Comment by yoshuawuyts** [comment]
I wonder if this is perhaps the same issue we're seeing here https://github.com/WebAssembly/wasi-http/pull/114#issuecomment-2197661559 ?

```text
thread 'main' panicked at /Users/yosh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-parser-0.209.1/src/resolve.rs:2105:21:
assertion `left == right` failed
  left: Interface { id: Id { idx: 1 }, stability: Stable { since: Version { major: 0, minor: 2, patch: 0 }, feature: None } }
 right: Interface { id: Id { idx: 1 }, stability: Unknown }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by yoshuawuyts** [comment]
I went ahead and tested https://github.com/bytecodealliance/wasm-tools/pull/1669 as part of a local `wit-bindgen` build. That seems to work to resolve the issue in https://github.com/WebAssembly/wasi-http/pull/114#issuecomment-2197661559!

**Comment by vados-cosmonic** [comment]
Thanks for the super quick resolution on this @alexcrichton :bow:
