### ISSUE TITLE
`wit-parser::decoding::decode` should error when given a core module

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/wasm-tools#1673]
`wit-parser::decoding::decode` requires a WebAssembly component (either as a normal component or as a WIT-package-encoded-as-binary). However, if you pass in a core module, everything "works" (i.e., no error is returned), but you end up with an empty resolve. I imagine the right thing to do here would be to error specifying that a component must be passed. 

Let me know if this is the case, and I can submit a fix.

**Comment by alexcrichton** [comment]
One use case of passing a core module is that there's these `*.o` files that come out of wit-bindgen with world information and I wanted to support `wasm-tools component wit` on these files. I don't believe that's tested in this repository though and I'm not sure if it still works at all. That leads me to:

* If that doesn't work, then I think it's reasonable to just return an error saying that core modules aren't supported.
* If that does work, then a core module with zero custom sections that look like `component-type*` should return an error

**Comment by ChristofPetig** [comment]
I have used `wasm-tools component wit` on core modules containing the section in the past and it worked fine. Given the wasit2 idea (core modules with WIT interfaces, I didn't find a link easily, it was around the SIG embedded discussion) I would recommend to go for the second choice.
