### ISSUE TITLE
ResizableLimits can't represent the maximum memory32 heap size of 4GB

### ISSUE THREAD

**Issue by lars-t-hansen** [bytecodealliance/wasm-tools#168]
Cf https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasmparser/src/primitives.rs#L196.  The maximum heap size for memory32 is 4GB (64K pages of 64K bytes each), but as this structure uses a u32 for the maximum field, and this field appears to represent a number of bytes and not the largest valid index, the maximum size cannot be represented.  The structure should probably use u64 fields.

(Firefox is changing to support 4GB heaps, and we use wasmparser.)

**Comment by alexcrichton** [comment]
I think the `ResizableLimits` just stores the raw u32 we read from the wasm binary itself (pages, not bytes), so I think this should be handled already? Although I could be missing a spot where we try to translate that to bytes by accident. I believe the intention is that it's always listed in pages.

**Comment by lars-t-hansen** [comment]
Cranelift bug, then - it treats this as bytes.  I'll fix locally.
