### ISSUE TITLE
`merge_worlds` on `wit_parser::resolve::Resolve` fails when worlds contain the same export 

### ISSUE THREAD

**Issue by karthik2804** [bytecodealliance/wasm-tools#1685]
While trying to merge multiple worlds, I noticed worlds with the same exports could not be merged (i.e.) if 2 worlds export wasi:http/incoming-handler@0.2.0, the worlds cannot be merged. 
```
export `wasi:http/incoming-handler@0.2.0` conflicts with the previous name of `wasi:http/incoming-handler@0.2.0`
```

The expected behavior would be for the worlds to merge successfully as long as the types of exports are the same.

Here is a [repo](https://github.com/karthik2804/wit-parser-merge-issue) with an example of it

**Comment by alexcrichton** [comment]
Debugging this a bit this is also related to https://github.com/bytecodealliance/wit-bindgen/pull/1007 and the relevant code is [all here in `merge_worlds`](https://github.com/bytecodealliance/wasm-tools/blob/263b697a442273ef9848e73546c770f5b7f6e2a9/crates/wit-parser/src/resolve.rs#L725). The basic problem this function is trying to take care of is that a core module might have multiple `component-type:*` sections within it generated by different bindings generator. Each section has a single world representing its bindings, and so this function is merging all the worlds into one so the unit of componentization is a single `World`.

The current implementation I believe was written during a time where worlds were sturctured differently (I think it was when we did `import foo: bar;`) and is a bit wonky today. The general idea is that imports can be freely unioned but exports a bit weirder. Originally the thinking was that you can union disjoint exports, but even that's not actually true. Overall the implementation is basically very surprising semantically.

That leaves us with the question of what to do about this. I'm personally at a bit of a loss. The whole concept of merging things together is already sort of nebulous and best-effort at best. There's also a whole separate path of merging in `Resolve::merge` which is similar but subtly different than `merge_worlds`.  I'm trying to reboot all this context and figure out the best way out of this rut.

For now this can be reproduced with a test in this repository with:

```wit
// RUN: component embed --dummy --world foo % | component embed --world foo % | component wit

// This test embeds this world twice and then ensures that merging the two
// worlds together works (it's the same definition anyway).

package a:b;

interface x {
  type t = u32;
}

world foo {
  import x;
  export x; // just this is necessary to reproduce this issue

  use x.{t}; // just this is required to reproduce wit-bindgen#1007

  import a: func() -> t;
}
```

which reproduces both this issue  and https://github.com/bytecodealliance/wit-bindgen/pull/1007
