### ISSUE TITLE
Proposed tool: WASM binary output crate

### ISSUE THREAD

**Issue by icefoxen** [bytecodealliance/wasm-tools#17]
This is like the single wasm-related tool I *can't* find here: something to take a Webassembly AST or slightly-more-convenient data structure, and output binary wasm.  I'm writing a compiler backend that outputs wasm binary format, and having a known-correct crate that does this for me would be super convenient.  I'm currently using `parity-wasm`, which works but is not exactly convenient or up to date, lacking things like multiple value returns.  It looks like the wasmtime `wast` library also has the functionality I want, but is inconvenient in different ways; there's not much point in the compiler backend worrying about function names and code spans and such, and the docs don't really demonstrate how to go straight from AST to binary without starting by parsing text.  There's also some cases like the `Id` type, which apparently can't be constructed at all *except* by the parser.  So trying to use it for conjuring wasm from nothing would result in a pile of PR's to add the needed functionality.

So, is the functionality of taking a more binary-specific AST and outputting wasm bytecode something that would be interesting if I were contribute it?

Thanks in advance.

**Comment by fitzgen** [comment]
Does [the `walrus` crate](https://github.com/rustwasm/walrus) fit your needs?

An idea we've been kicking around, but no one has gotten around to yet, is splitting out `walrus`'s wasm encoder for inclusion in this repo, so that it could be used without the higher-level bits of `walrus` (but also, it sounds like you want those higher-level bits).

**Comment by icefoxen** [comment]
Ooh, `walrus` might be quite interesting, thank you!

...also, fitzgen, is there any part of the Rust ecosystem that HASN'T had most of the foundations written by you, alexcrichton or bluss? XD

**Comment by fitzgen** [comment]
heh, Alex is on a whole 'nother level :-p

Would you consider this issue resolved? Should we close it?

**Comment by icefoxen** [comment]
Yeah, though you might consider searchability for `walrus` (in your copious free time, I'm sure).  I tried pretty hard to find anything that looked good off of crates.io and here and didn't turn it up.  Didn't think to look through `wasm-bindgen` stuff though.

Thanks a lot!
