### ISSUE TITLE
wast lexer size assert not compatible with randomized struct layouts

### ISSUE THREAD

**Issue by the8472** [bytecodealliance/wasm-tools#1750]
https://github.com/bytecodealliance/wasm-tools/blob/d68b3828f0ebbc46ce0b4fff9c4d5d881487114a/crates/wast/src/lexer.rs#L64-L66

breaks when compiling with [layout randomization](https://github.com/rust-lang/rust/issues/106764)

If the assert is necessary for correctness then `repr(C)` should be used to get a deterministic layout.
If it's just an optimization then it's probably better to just check it in tests/CI.

Found this while trying to build the rust compiler with randomized layouts. https://github.com/rust-lang/rust/pull/101339

**Comment by alexcrichton** [comment]
Thanks for the report, and sorry for the breakage! Is this something that you'd prefer to see urgently fixed? If so I can work on getting a patch release out for rust-lang/rust to update to. (it's a bit nonstandard to do patch releases in this repo unfortunately but I can make it work)

**Comment by the8472** [comment]
Not urgent, I can probably work around it for now by excluding a bunch of things from randomization.
I see that wast is updated monthly or so, that should be fine.

**Comment by the8472** [comment]
Looks like that wasn't sufficient, there are another compile time size assert:

https://github.com/bytecodealliance/wasm-tools/blob/537ca81024e47b349551a95ab6ecba229f3795ba/crates/wast/src/core/expr.rs#L1214

**Comment by the8472** [comment]
There are more

https://github.com/bytecodealliance/wasm-tools/blob/537ca81024e47b349551a95ab6ecba229f3795ba/crates/wasmparser/src/validator/types.rs#L109-L111

generally all such asserts should be moved to tests, otherwise the crates break under layout randomization.

**Comment by alexcrichton** [comment]
Oops, thanks for pointing that out! I've submitted https://github.com/bytecodealliance/wasm-tools/pull/1894 to relax some more assertions.

To confirm though, in the [second case you mentioned](https://github.com/bytecodealliance/wasm-tools/issues/1750#issuecomment-2453481023), that assert is technically ok to leave as a const-assert right? It's an assertion about a `#[repr(C)]` structure which `-Zrandomize-layouts` doesn't affect, right?

**Comment by the8472** [comment]
Oh yeah, I didn't look at the struct declaration. That one is fine.
