### ISSUE TITLE
wit-parser: the serialized function struct should reserve explicitID

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wasm-tools#1768]
Consider the following WIT file

```wit
package foo:foo;

interface conventions {
  // Identifiers with the same name as keywords are quoted.
  %bool: func();
}

world the-world {
  import conventions;
  export conventions;
}
```

The `%bool` function has a `Token::ExplicitId` and in `parse_id()` the symbol `%` is striped away, resulting the serialized `Function` struct that has difference between explicitID vs. ID, i.e.

```json
"interfaces": [
    {
      "name": "conventions",
      "types": {},
      "functions": {
        "bool": {
          "name": "bool",
          "kind": "freestanding",
          "params": [],
          "results": [],
          "docs": {
            "contents": "Identifiers with the same name as keywords are quoted."
          }
        }
      },
      "package": 0
    }
  ],
```

which could be an issue for tools like https://github.com/ydnar/wasm-tools-go because turning the json back to wit is not possible anymore. cc @ydnar

**Comment by alexcrichton** [comment]
(or, alternatively, that's something that `wasm-tools` could possibly implement too: "ingest this JSON and output WIT"

**Comment by Mossaka** [comment]
yeah I realized a simple solution is to re-add `%` character back to the WIT keywords in wit-bindgen-go and in fact it's already doing so. So gonna close this issue now. Thanks!

**Comment by ydnar** [comment]
Isn't % encoding only in WIT? Eg the function would be named `bool` in the resolve struct (here and in Go)? The Go code generation handles collisions with Go keywords (including `bool`).
