### ISSUE TITLE
wave: Can't parse function calls with empty arguments

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#1816]
Using [`UntypedFuncCall`](https://docs.rs/wasm-wave/latest/wasm_wave/untyped/struct.UntypedFuncCall.html) wave can't currently parse `f()` and yields the error `empty tuple at 1..3`. I think this is due to [function arguments being parsed as a tuple](https://github.com/bytecodealliance/wasm-tools/blob/6fc5d68b30931db5e9639a5cecf107fdf1bef894/crates/wasm-wave/src/parser.rs#L54) and tuples in general cannot be empty.

cc @lann

**Comment by lann** [comment]
Makes sense. Should be a quick fix.

**Comment by lann** [comment]
#1817
