### ISSUE TITLE
cargo test sometimes fails with `Broken pipe (os error 32)` under aarch64

### ISSUE THREAD

**Issue by ereslibre** [bytecodealliance/wasm-tools#1820]
Hello!

This bug is not always reproducible, but in my environment happens around ~60% of the runs. One example of the failure:

```shell-session
❯ cargo test -p wasm-tools --all

...

test "tests/cli/semver-check-add-imports.wit"                                  ... ok
test "tests/cli/add-metadata.wat"                                              ... ok
test "tests/cli/world-merging-export-conflict.wit"                             ... ok

failures:

---- "tests/cli/unbundle-print-module1.wat" ----
failed test "tests/cli/unbundle-print-module1.wat"

Caused by:
    Broken pipe (os error 32)


failures:
    "tests/cli/unbundle-print-module1.wat"

test result: FAILED. 105 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s

error: test failed, to rerun pass `-p wasm-tools --test cli`
```

Sometimes it's this test, sometimes it's others. Another example: https://github.com/NixOS/nixpkgs/pull/341059#issuecomment-2343590484

What all failing tests have in common though, is that they use the tmpdir and pipe feature of the tests.

I can confirm that I could not reproduce the issue after setting `--test-threads=1` during the `cargo test` execution, like:

```
$ cargo test -p wasm-tools --all -- --test-threads=1
```

**Comment by alexcrichton** [comment]
Thanks for the report, and sorry for the breakage! This should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1821

**Comment by ereslibre** [comment]
Oh wow, lightning fast; thanks a ton @alexcrichton!
