### ISSUE TITLE
wasm-tools parse converts a Wasm 1.0 .wat file to a non-1.0 .wasm file

### ISSUE THREAD

**Issue by womeier** [bytecodealliance/wasm-tools#1827]
I have a `.wat` file that only uses Wasm 1.0 features, however `wasm-tools` does not generate a 1.0 `.wasm` binary.
(`wat2wasm` _does_ generate a 1.0 binary, but I've had many issues with it and would like to use `wasm-tools` instead)

Is it a goal of `wasm-tools` to produce 1.0 binaries whenever possible? (if not, feel free to close)

# Reproduce
1) `make run-wat2wasm-success` works as expected
2) `make run-wasm-tools-fail` fails with `InvalidError(Only table index 0 is supported.)` of Concordium's Wasm engine, which is restricted to Wasm 1.0 (It seems related to the multi-table extension)
- wasm-tools 1.217.0
- [bug_report.zip](https://github.com/user-attachments/files/17147305/bug_report.zip)

**Comment by alexcrichton** [comment]
Thanks for the report! What originally produced the `*.wat` file? That file at the end has:

```wasm
  (elem (;0;) (i32.const 0) funcref (ref.func 0))
  (elem (;1;) (i32.const 1) funcref (ref.func 1))
```

which is using syntax (both text and binary) from the reference types proposal. Changing that to:

```wasm
  (elem (;0;) (i32.const 0) func 0)
  (elem (;1;) (i32.const 1) func 1)
```

causes `wasm-tools validate -f wasm1 ./counter_out.wat` to pass for me.

**Comment by womeier** [comment]
Ah, it seems `wasm-tools` works as expected, just `wasm2wat` printing it to Wasm 1.0 style is what surprised me.

I was using an outdated version of another tool that didn't yet have a fix for that.
