### ISSUE TITLE
`wasm-tools component unbundle` issues

### ISSUE THREAD

**Issue by SingleAccretion** [bytecodealliance/wasm-tools#1829]
1) The README lists it under `wasm-tools --> metadata <-- unbundle` while it should be `wasm-tools component unbundle`.
2) Why does the command want to output the decompiled component by default?

Re `2`: using `wasm-tools component unbundle --module-dir . component.wasm` as-is leads to:
```
error: cannot print binary wasm output to a terminal, pass the `-t` flag to print the text format
```
Which can be worked around with `wasm-tools component unbundle --module-dir . component.wasm > /dev/null` easily enough, but it does not seems like something that should be necessary.

**Comment by alexcrichton** [comment]
Oops the README bit is a copy/paste error on my part.

For (2) though the `unbundle` command both extracts the core wasm modules and additionally emits a new component that imports these core wasm modules. The component is the output of the command, but if you want to ignore it then piping to `/dev/null` or `-o /dev/null` should work yeah.

**Comment by SingleAccretion** [comment]
> For (2) though the unbundle command both extracts the core wasm modules and additionally emits a new component that imports these core wasm modules. The component is the output of the command, but if you want to ignore it then piping to /dev/null or -o /dev/null should work yeah.

So you would say that if, purely hypothetically of course 😄, there was a feature request for this command to "extract" a single core module from a component (to be further inspected via tools that only work with core components), it would be better to create a new command than extend `unbundle` with a flag?

**Comment by alexcrichton** [comment]
Perhaps yeah! There's not a ton of rhyme or reason for the current set of commands, it's mostly what I've found useful when doing things. In that sense a new one is always welcome :)
