### ISSUE TITLE
Compiling wat back to wasm?

### ISSUE THREAD

**Issue by noobdoesre** [bytecodealliance/wasm-tools#1833]
I checked wabt and binaryen projects, they do not support features like recursive types, that are present in a module I'm playing with.

So, I wonder whether there is a public tool that can handle wat2wasm with latest proposals implemented. Thanks!

**Comment by alexcrichton** [comment]
This project supports that with the `wast` or `wat` crates, which on the CLI is `wasm-tools parse` (some examples in the [README](https://github.com/bytecodealliance/wasm-tools?tab=readme-ov-file#examples))

Does that work for your use case?

**Comment by noobdoesre** [comment]
That's what I need, thanks!

**Comment by alexcrichton** [comment]
Great! In that case I'm going to close this. Feel free to comment though if something is amiss!
