### ISSUE TITLE
duplicate export name `57` already defined when importing multiple semver versions

### ISSUE THREAD

**Issue by jsturtevant** [bytecodealliance/wasm-tools#1850]
Using the latest wasi-sdk pacakge built with the fix from https://github.com/bytecodealliance/wasm-tools/issues/1774 (https://github.com/WebAssembly/wasi-sdk/actions/runs/11129514597) I still get an error when building a wasm component with `wasi:io/poll@0.2.0` and `wasi:io/poll@0.2.1` I get the following error:

```
-- Build files have been written to: /home/jstur/projects/runtime/artifacts/bin/native/net10.0-wasi-Debug-wasm
  [ 14%] Linking C executable dotnet.wasm
EXEC : error : failed to encode component [/home/jstur/projects/runtime/src/mono/wasi/wasi.proj]

  Caused by:
      0: failed to validate component output
      1: duplicate export name `57` already defined (at offset 0xdf82f5)
```

```
cat /home/jstur/wasi-sdk-nightly/VERSION
24.9gcec5cf4f6cf3
wasi-libc: 1b19fc65ad84
llvm: a4bf6cd7cfb1
llvm-version: 19.1.0
config: f992bcc08219
```

**Comment by alexcrichton** [comment]
I think this should be fixed in https://github.com/bytecodealliance/wasm-tools/pull/1851. Is it desired that .NET updates to the latest wasi-sdk in the near future? There's a number of places to update after that lands and I'm wondering if that should happen "sooner rather than later" or if a normal "on demand" cadence is ok.

**Comment by pavelsavara** [comment]
These days we are also upgrading mono to LLVM 19 https://github.com/dotnet/runtime/pull/105427 
It would be good to have wasi-sdk target aligned. Is the planned version wasi-sdk 25 going to be LLVM 19 ?

**Comment by alexcrichton** [comment]
Yeah wasi-sdk 25 will have LLVM 19, it's already merged there just hasn't been a release yet.

**Comment by jsturtevant** [comment]
I am happy to try out the prerelease bits once this makes its way to the wasi-sdk repo
