### ISSUE TITLE
Missing Dwarf symbols with wasm-tools component new

### ISSUE THREAD

**Issue by ggjjj** [bytecodealliance/wasm-tools#1854]
1. I have a sample wasm module that is built in rust and in debug mode by `cargo build --target wasm32-wasip1 -p module1`
2. Next I check the dwarf sections by using the `wasi-sdk` by `llvm-dwarf ./module1.wasm` -> I can see the DWARF sections
3. Then I create a new component model by `wasm-tools component new ./target/wasm32-wasip1/debug/module1.wasm -o ./tests/wasm-modules/module1-v1.wasm --adapt wasi_snapshot_preview1.reactor.wasm`
4. But once I again use the `llvm-dwardf ./module1-v1.wasm` it gives this error

**invalid version number: 65549**

**wasi snapshot**
https://github.com/bytecodealliance/wasmtime/releases/download/v24.0.0/wasi_snapshot_preview1.reactor.wasm

Tried with `wasm-objdump` as well

./wabt/build/wasm-objdump -x ./tests/data/wasm-modules/processor-module1-v1.wasm 

**0000008: error: bad wasm file version: 0x1000d (expected 0x1)**
Can someone help me if I am doing the right way to analyze?

**Comment by alexcrichton** [comment]
Thanks for the report! What you're running into here is that the output of `wasm-tools component new` is a component, not a core wasm module. The binary format for those are different and is reflected in the version word in the header of the file. 

What's the end goal of what you're trying to accomplish? Both `llvm-dwarf` and `wabt` don't have support for components, but `wasm-tools` does. For example `wasm-tools objdump ...` can print some headers. What you're trying to do though may not be supported by the `wasm-tools` CLI though.

**Comment by ggjjj** [comment]
@alexcrichton  Thanks Alex for your inputs. With the `wasm-tools objdump` I think I can see that the ./**tests/wasm-modules/module1-v1.wasm** has debug information.

custom ".debug_abbrev"               |    0x5b4c4 -    0x6496a |     38054 bytes | 1 count
    custom ".debug_info"                 |    0x6497a -   0x16f125 |   1091499 bytes | 1 count
    custom ".debug_ranges"               |   0x16f137 -   0x1a95c7 |    238736 bytes | 1 count
    custom ".debug_str"                  |   0x1a95d6 -   0x31120d |   1473591 bytes | 1 count
    custom ".debug_line"                 |   0x31121d -   0x37e598 |    447355 bytes | 1 count
    
   The reason of getting these dumps is to some breakpoint debugging..

 What I am trying to do is to debug (LLDB debug) a rust application that launches the wasm runtime along with one wasm module (component model) and step into the source code of the wasm module. Is that possible with the above .wasm file? 
 
 Currently the breakpoint doesn't get hit.

I do configure the runtime with debug_info() set to true

**Comment by ggjjj** [comment]
wasmtime-wasi = { version = "24" }
snapshot version https://github.com/bytecodealliance/wasmtime/releases/download/v24.0.0/wasi_snapshot_preview1.reactor.wasm 

is this supported?

**Comment by alexcrichton** [comment]
Yes 24.0.x should be supported. Note that the crate that matters here is the `wasmtime` crate itself. That version will match `wasmtime-wasi` though so 24.0.x is fine. Also note that the adapter doesn't affect the issue here.

Do the docs [here](https://docs.wasmtime.dev/examples-debugging-native-debugger.html) help at all? If not mind opening an issue on the Wasmtime repository?

**Comment by ggjjj** [comment]
For some reason 24.0.0 did not work but with recent 25.0.2 It work fine. So closing this issue
