### ISSUE TITLE
bug: automated releases need to consider `wit` test

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#1915]
When publishing a new major `wasm-tools` version the scripts stumbled upon a test that was not properly updated:

Publish PR: https://github.com/bytecodealliance/wasm-tools/pull/1914
Problematic test: https://github.com/bytecodealliance/wasm-tools/pull/1914/commits/b3ac2d13aefdf4648a4dd1a77009e8828d824ae4

The fix was trivial: changing `220` to `221` but this should be included in the automated scripts OR should not need adjustment at all.

cc @alexcrichton

**Comment by pchickey** [comment]
This bit me too so I did a probably not that questionable fix in #1916.
