### ISSUE TITLE
`wasmprinter`: make indent character configurable

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/wasm-tools#1962]
I find the indentation is not very noticeable when reading nested blocks.

I wish it could be increased to 8 spaces.

Do I just need to modify this place and add the configuration item:

https://github.com/bytecodealliance/wasm-tools/blob/57b1acee689e49f43338e4efb15b65e9f922831d/crates/wasmprinter/src/lib.rs#L1416

**Comment by alexcrichton** [comment]
Sounds reasonable to me yeah!
