### ISSUE TITLE
Please include wasm-encoder in the main README

### ISSUE THREAD

**Issue by renatoathaydes** [bytecodealliance/wasm-tools#201]
Hi!

I've noticed that [wasm-encoder](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-encoder) is not mentioned in the README.

Is there a reason for that?

I was looking for a binary generator and had trouble finding one, and because `wasm-encoder` is not mentioned in the README of this project, I wasted quite some time trying some other libraries which do not seem to be maintained anymore and are riddled with bugs.

Since I found `wasm-encoder`, it has worked perfectly for me, so far! Thanks for the good job.

Could you please also mention it in [Crates you should know](https://rustwasm.github.io/book/reference/crates.html#parsing-and-generating-wasm-binaries) document while you're at it?

Thanks again.

**Comment by alexcrichton** [comment]
Oops indeed! Added at https://github.com/bytecodealliance/wasm-tools/pull/204

**Comment by renatoathaydes** [comment]
Thanks.
