### ISSUE TITLE
Why are section ids read as var u7 in wasmparser?

### ISSUE THREAD

**Issue by imor** [bytecodealliance/wasm-tools#203]
The spec says that a [section id is a byte](https://webassembly.github.io/spec/core/binary/modules.html#sections), why are then the section ids in wasmparser [read as a var u7](https://github.com/bytecodealliance/wasm-tools/blob/3a44ae1344a75727d56a8df5772d701514040785/crates/wasmparser/src/parser.rs#L465)? I know there is no practical difference between the two interpretations as the number of valid section ids are too few to matter but was just curious about this difference.

**Comment by alexcrichton** [comment]
@yurydelendik do you know this perhaps?

**Comment by yurydelendik** [comment]
Indeed spec says it is one byte but does not define its type in the referenced section.

There is also https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure , which says
```
id | varuint7 | section code
```

**Comment by alexcrichton** [comment]
Oh I think at this point `BinaryEncoding.md` is a bit out-of-date and/or not maintained, but the [official spec](https://webassembly.github.io/spec/core/binary/modules.html#sections) defines this as a singular byte?

**Comment by imor** [comment]
@yurydelendik If the original implementation was based on the document that you shared, that does explain the var u7. Again pardon my nitpick but the spec says that [bytes encode themselves](https://webassembly.github.io/spec/core/binary/values.html#binary-byte) . As it doesn't make any difference to the parsed values, and my original question is answered, I'm closing this issue.

**Comment by imor** [comment]
@alexcrichton I don't know how I missed your last comment. Yes the official spec says that each section starts with a one byte section id.
