### ISSUE TITLE
License disambiguation

### ISSUE THREAD

**Issue by eclipseo** [bytecodealliance/wasm-tools#206]
The cargo.toml  and README specify the license as Apache-2.0 WITH LLVM-exception but the crate contains both LICENSE-APACHE and LICENSE-MIT files.
Please explain under what license is this program distributed.

Thanks.

**Comment by alexcrichton** [comment]
Sorry for the confusion! The intention is that everything here is Apache-2.0 WITH LLVM-exception licensed. The wasm-smith crate was fixed in https://github.com/bytecodealliance/wasm-tools/pull/210 and the `wast` crate is being clarified in https://github.com/bytecodealliance/wasm-tools/pull/211

**Comment by eclipseo** [comment]
Than's, I will report downstream.
