### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasm-tools#27]
As a policy, the Bytecode Alliance is changing the default branch names in all repositories. We would like for all projects to change the default to `main` by June 26. (We mention June 26th because there is some suggestion that GitHub may be adding the ability to make this process more seamless. Feel free to wait for that, but only up to June 26. We'll provide further support and documentation before that date.)

Please consider this a tracking issue. It is not intended for public debate.

- [ ] Change branch name
- [ ] Update CI
- [ ] Update build scripts
- [ ] Update documentation

**Comment by alexcrichton** [comment]
Done now!
