### ISSUE TITLE
Accessing `ValidatorResources` from `Validator`

### ISSUE THREAD

**Issue by harpocrates** [bytecodealliance/wasm-tools#271]
There doesn't seem to be a way to get a `ValidatorResources` from a `Validator`, only from the `FuncValidator` obtained in a code section entry. Is this intentional?

I was trying to follow the advice in the docs for `Validator`:

> The design of Validator is intended that you’ll interleave, in your own application’s processing, calls to validation. Each variant, after it’s received, will be validated and then your application would proceed as usual. At all times, however, you’ll have access to the Validator and the validation context up to that point. This enables applications to check the types of functions and learn how many globals there are, for example.

I found myself wanting to query types when processing an export section, and realized that's actually not possible (so I guess that code has to move to when the function is being processed).

**Comment by alexcrichton** [comment]
I think that this was added [quite recently](https://github.com/bytecodealliance/wasm-tools/pull/268), although it hasn't been published yet. Would that work for your use case?

**Comment by harpocrates** [comment]
That's _exactly_ the implementation I initially assumed existed and was surprised to not find. Thank you for the link!

Roughly how often does `wasmparser` publish to crates.io (or more specifically: is there a date for the next release)? I'm asking to gauge whether it is worth switching cargo to use a git dependency on `wasmparser`.

**Comment by alexcrichton** [comment]
Nah we generally just release as-needed, so I posted https://github.com/bytecodealliance/wasm-tools/pull/272 to release this.

**Comment by harpocrates** [comment]
Thank you! ❤️

**Comment by alexcrichton** [comment]
Ah yes that was indeed accidental, and should be fine to re-add
