### ISSUE TITLE
wasm-smith: alignment (0) must be a power of 2

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasm-tools#281]
When generating modules, I frequently see errors like the following when I validate with WABT's wasm2wat: `test.wasm:00001a2: error: alignment (0) must be a power of 2`. This could be one of two things:
 - WABT's [`is_power_of_two`](https://github.com/WebAssembly/wabt/blob/9719aa5b0cb3ce03696d255423dabb14c2d289c8/src/shared-validator.cc#L570-L572) calculation could be too restrictive
 - wasm-smith's use of `alignments` like `&[0, 1, ...]` is incorrect for `0`.

The following generated sample demonstrates the error: [test.wasm.txt](https://github.com/bytecodealliance/wasm-tools/files/6620210/test.wasm.txt).

**Comment by abrown** [comment]
cc: @fitzgen, @alexcrichton

**Comment by alexcrichton** [comment]
I think this may be a bug in wabt? Wabt is rejecting this file but I'm pretty sure it should be accepted. There's actually no way to represent an alignment of 0 in the binary format, it's stored as log2 so it's fundamentally always a power of 2.

```wasm
(module
  (memory 1)
  (func
      i32.const 0
      v128.const i32x4 0 0 0 0
      v128.load32_lane align=1 0
      drop
  )
)
```

**Comment by abrown** [comment]
Hm, yeah, `wasm-encoder` seems to just [pass through the alignment number](https://github.com/bytecodealliance/wasm-tools/blob/9956d1408d9601ca88bdff072eb642eb224ffbd1/crates/wasm-encoder/src/code.rs#L154-L165) (though I don't understand the `self.align | 1 << 6`, @fitzgen?) and this seems correct: looking around (e.g. https://github.com/WebAssembly/wabt/issues/1567), the encoded Wasm should have the "power of" number while the decoded WAT should have the "number of bytes." Opened https://github.com/WebAssembly/wabt/issues/1674.

**Comment by alexcrichton** [comment]
I think this ended up not being a bug in this crate, so I'm gonna close this.
