### ISSUE TITLE
Make wasmparser no_std again

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasm-tools#3]
There is still intent to support "no_std" feature for this crate. There is no need to support allocation hungry API such as `WasmParser`/`WasmDecoder`, so it will be beneficial to make this legacy API under feature -- the section readers is more performant API and has to be used at this moment. 

TODOs:
- [ ] Make `WasmParser` and friends optional via feature (and/or deprecate)
- [ ] Cleanup sections readers to not use dynamic memory `Box`, `Vec`, `HashMap`

I think that will allow us to be `no_std` without depending on `alloc` or `hashbrown` crates.

**Comment by Robbepop** [comment]
In case anyone requires `no_std` support for the `wasmparser` crate: I am maintaining a `no_std` fork for embedded environments here: https://crates.io/crates/wasmparser-nostd

**Comment by alexcrichton** [comment]
For anyone interested I've opened https://github.com/bytecodealliance/wasmtime/issues/8341 which is for Wasmtime but would extend to wasmparser since it's a dependency and would be required as well.

**Comment by alexcrichton** [comment]
Done now in https://github.com/bytecodealliance/wasm-tools/pull/1493, so closing.
