### ISSUE TITLE
MemArg must not limit offset to u32

### ISSUE THREAD

**Issue by lars-t-hansen** [bytecodealliance/wasm-tools#317]
With memory64 coming, the `offset` of any access may be an u64, and MemArg must be updated to accomodate this: the offset field must be u64.  Also the MemArg parser must not error out if the value exceeds the range of an u32.

Presumably this change will snowball throughout the system in some interesting ways.

**Comment by alexcrichton** [comment]
I think this was updated in https://github.com/bytecodealliance/wasm-tools/pull/300 and recently published as well, but are you using a version from after that commit and is it still not working? (I thought I got everything but there may be something I'm missing

**Comment by lars-t-hansen** [comment]
Hm, the source on main (just pulled an update) has the field as u32 and has a guard on overflow...  This is for the text format, mind you.  What you're pointing to looks like it's about the binary format.

**Comment by alexcrichton** [comment]
Hm are we looking at perhaps different structs? I know that memarg is defined in a whole bunch of places... In `wast` though here is where it was updated to `u64`:

https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wast/src/ast/expr.rs#L1242-L1243

Is there somewhere else though I missed in the updates?

**Comment by lars-t-hansen** [comment]
weird...  that's where i'm looking, so why am i not seeing that code?  investigating...
