### ISSUE TITLE
encode function for wasm-encoder structs

### ISSUE THREAD

**Issue by Jacarte** [bytecodealliance/wasm-tools#330]
Hi all,

Is there any particular reason about why the `encode` function inside some wasm-encoder structs is private ? For example here, https://github.com/bytecodealliance/wasm-tools/blob/85622cc0f872c4aca85510e181437b149234453c/crates/wasm-encoder/src/code.rs#L141
 
I want to collect the generated bytes only for the function locals and its body, I set this declaration to public and it worked. But I am probably missing something here :)

Thanks in advance

**Comment by fitzgen** [comment]
Generally we would use the `wasm_encoder::CodeSection::function` method to add the function to a code section, which will internally call `wasm_encoder::Function::encode`:

https://github.com/bytecodealliance/wasm-tools/blob/85622cc0f872c4aca85510e181437b149234453c/crates/wasm-encoder/src/code.rs#L54-L59

That said, if there is a motivating reason why one might want to encode a function without adding it directly to a code section, then we can make it `pub`.
