### ISSUE TITLE
Usage of `wasmparser::Validator` for function bodies

### ISSUE THREAD

**Issue by ivan770** [bytecodealliance/wasm-tools#335]
Hi!

While implementing a tool based on `wasmparser` I found that there is a lack of information about validating function bodies. In particular, for any other resource but `FunctionBody` there exists an entry in `WasmModuleResources`, which kind of provides us a way to random-access WASM data (I know that `wasmparser` is not about random-access).

However, when validating a function `Validator` returns [ValidPayload::Func](https://docs.rs/wasmparser/0.80.1/wasmparser/enum.ValidPayload.html#variant.Func), but doesn't give any information on if the returned structs are related to each other or not (for example, [FuncValidator::finish](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.finish) specifies, that a function must be called for it to be validated correctly, but what is a "call"? Reading `FunctionBody`s `BinaryReader` up to the very end?)

Is there any guidance on how to use a `Validator` correctly (at least on function bodies)?

**Comment by alexcrichton** [comment]
Within `ValidPayload::Func` you'll find a `FuncValidator` as well as a `FunctionBody`. You can use [`FunctionBody::get_operators_reader`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FunctionBody.html#method.get_operators_reader) to read the operators of the function (and other readers there to read the locals). This operator and local information is passed to `FuncValidator` via methods like [`FuncValidator::op`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.op). You can also wholesale validate the entire body with [`FuncValidator::validate`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.validate)

Does that answer your question? Or is there something that could use improvement?

**Comment by ivan770** [comment]
> 
> 
> Within `ValidPayload::Func` you'll find a `FuncValidator` as well as a `FunctionBody`. You can use [`FunctionBody::get_operators_reader`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FunctionBody.html#method.get_operators_reader) to read the operators of the function (and other readers there to read the locals). This operator and local information is passed to `FuncValidator` via methods like [`FuncValidator::op`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.op). You can also wholesale validate the entire body with [`FuncValidator::validate`](https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.validate)
> 
> Does that answer your question? Or is there something that could use improvement?

My bad, I missed the meaning of _If this function is not called_ in https://docs.rs/wasmparser/0.80.1/wasmparser/struct.FuncValidator.html#method.finish and interpreted as _If the function being validated is not called_. Sorry for bothering.
