### ISSUE TITLE
Prototype Relaxed SIMD spec

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasm-tools#354]
See https://github.com/WebAssembly/relaxed-simd

There are currently few major items to address:
 - [ ] implement `fpenv` section
 - [x] implement operators

There is vague binary format specification at the moment, but looks like "all Relaxed SIMD instructions will take an additional varuint32 immediate, which is an index into the fpenv index space". It requires to specify/read a `varuint32` after SIMD op code. We can assume there will one section defined, and we can default the fpenv index value to 0 for now. There is some churn of symbolic names for WAT, so `relaxed` prefix may go away.

The section code for `fpenv` is hard to define at this phase. We can choose one e.g. `18` or `0`+`'fpenv'` for now. @sunfishcode wdyt? The section body will default to `01` (amount of entries) + `00` (recommended padding). Order somewhere between `Global` and `Export` (?)

/see https://bugzilla.mozilla.org/show_bug.cgi?id=1732996

**Comment by alexcrichton** [comment]
I believe this has since been done, so closing.
