### ISSUE TITLE
wasm-mutate produces invalid wasm module

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#379]
Similar to https://github.com/bytecodealliance/wasm-tools/issues/373, but perhaps a different fuzz bug! With [this input](https://github.com/bytecodealliance/wasm-tools/files/7453868/input.gz) this wasm:

```wasm
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i64.const -1
    i32.const -1
    i64.extend_i32_u
    i64.le_u)
  (data (;0;) ""))
```

is mutated into this:

```wasm
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i64.const -1
    i64.const -1
    i64.extend_i32_u
    i64.le_u
    i64.const -1
    i64.const -1
    i64.extend_i32_u
    i64.le_u
    i32.and)
  (data (;0;) ""))
```

and I believe the seed is 2377620224045154336

**Comment by alexcrichton** [comment]
cc @Jacarte @fitzgen

**Comment by Jacarte** [comment]
Hi @alexcrichton, this is already addressed in https://github.com/bytecodealliance/wasm-tools/pull/378. Waiting for review to merge ;)

**Comment by alexcrichton** [comment]
Oh nice! Disregard me then :)

(I'm just ferrying over bugs from oss-fuzz to here!)

**Comment by Jacarte** [comment]
> Oh nice! Disregard me then :)
> 
> (I'm just ferrying over bugs from oss-fuzz to here!)

Please keep doing so 😄

**Comment by Jacarte** [comment]
@alexcrichton this issue can be closed 😄
