### ISSUE TITLE
wasm-mutate: Timeout while fuzzing when mutating an medium-sized input

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#383]
We got a fuzz-bug last night for a timeout on oss-fuzz with wasm-mutate. [This input wasm file](https://github.com/bytecodealliance/wasm-tools/files/7475680/test.wasm.gz) with seed 724246166195997197 takes a fair bit of time to mutate locally:

```
$ time ./target/release/wasm-mutate --seed 724246166195997197 ./test.wasm -o output.wasm --preserve-semantics
./target/release/wasm-mutate --seed 724246166195997197 ./test.wasm -o    8.63s user 3.23s system 99% cpu 11.859 total
```

I noticed that `--preserve-semantics` is required to make this take a fair bit of time.

For reference @Jacarte the timeout on oss-fuzz is 60 seconds for any input, and fuzzing instrumentation typically slows things down by ~15-20x, which means we need to process all inputs in <3s without actual fuzzing instrumentation. Locally with a fuzzing build it looks like it takes ~140s to complete the fuzz run. For reference this is the [fuzz input](https://github.com/bytecodealliance/wasm-tools/files/7475705/input.gz).

**Comment by Jacarte** [comment]
Thanks @alexcrichton, we will probably need a timeout option for `wasm-mutate`. In the worst case if a peep mutation cannot me applied it will iterate thought all instructions, which is not practical

**Comment by Jacarte** [comment]
> Thanks @alexcrichton, we will probably need a timeout option for `wasm-mutate`. In the worst case if a peep mutation cannot me applied it will iterate thought all instructions, which is not practical

Actually, this is the case, `[2021-11-04T15:31:15Z INFO  wasm_mutate::mutators::peephole] 1 / 20480 (0.00%) mutated operators.` It tries to mutate 20480 instructions before finding a good mutation point

**Comment by fitzgen** [comment]
> It tries to mutate 20480 instructions before finding a good mutation point

Is it trying to mutate the function that is mostly `drop`s inside unreachable code? I assume so.

I think we should ideally be able to mutate these `drop`s. The unfold mutation should work on them, as should inserting any stack-neutral snippet of code.

Ideally, there shouldn't be any large sequence of code where we can't apply some kind of mutation.

> we will probably need a timeout option for `wasm-mutate`

Ideally, we want to maintain determinism, so I would prefer a "fuel" mechanism over a timeout.

**Comment by alexcrichton** [comment]
I would agree with @fitzgen on both counts, both that ideally we wouldn't need timeout/fuel/etc and could process even medium-sized modules like this promptly. I don't know the source of the slowdown though or whether that's feasible in this case.

Otherwise though definitely agreed we would want some sort of fuel mechanism instead of a timeout. Timeouts are actually quite tricky to implement and especially for fuzzing the more determinism the better.

Eventually we'll probably want to hook wasm-mutate up to all other fuzzers as well. In that sense that's why I think it would be best to cover as most inputs as possible, but otherwise fuel provides us a means of controlling how much time is taken for the mutation.
