### ISSUE TITLE
wasm-mutate: Mutate use-of-value to instead be use-of-global

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#391]
In Wasmtime one thing we try to optimize is memory operands in the generated code, folding address operations into instructions themselves instead of having a separate load instruction. This is a pretty complex part of Wasmtime and it's a good one to stress while fuzzing, so while talking today with @fitzgen I had the idea where a possible mutator for wasm when preserving semantics could be:

* For any time a value of type `T` is used
* Insert a new `(global $new_global (mut T) (T.const $zero))`
* Just before the usage do `global.set $new_global global.get $new_global`

At least in wasmtime `global.{get,set}` are implemented with raw loads/stores so this could help stress the logic for folding loads/stores into other surrounding instructions.

cc @Jacarte

**Comment by Jacarte** [comment]
Cool ! thanks

**Comment by fitzgen** [comment]
Probably one invocation of `wasm-mutate` would only do this for one type in one function. No need to rewrite the whole binary every time, we can do it incrementally via multiple calls into `wasm-mutate`.

**Comment by Jacarte** [comment]
With the current implementation of the peepholemutator we can create a custom rewriting rule. Something like `?x => use_new_global`. The custom `use_new_global` operator encodes the instructions `global.set $new global.get $new` and also modifies the module structure to add the new global.

**Comment by fitzgen** [comment]
Fixed in #397
