### ISSUE TITLE
`wasm-mutate` produces an invalid Wasm file

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasm-tools#409]
Fuzz input: [fuzz.gz](https://github.com/bytecodealliance/wasm-tools/files/7651494/fuzz.gz)

commit 061f7dd19e217b62ecb34f8cec683316be3107fd

seed = 18374865303839425951

<details><summary>Initial Wasm</summary>

```wat
(module
  (type (;0;) (func (result f32)))
  (func (;0;) (type 0) (result f32)
    f32.const 0x0p+0 (;=0;))
  (elem (;0;) declare externref))
```

</details>

<details><summary>Mutated Wasm</summary>

```wat
(module
  (type (;0;) (func (result f32)))
  (func (;0;) (type 0) (result f32)
    f32.const 0x0p+0 (;=0;)
    f32.const 0x0p+0 (;=0;)
    f32.add
    f32.const 0x0p+0 (;=0;)
    f32.const 0x0p+0 (;=0;)
    f32.add
    f32.add)
  (elem (;0;) declare externref))
```

</details>

Validation error:

```
Err(BinaryReaderError { inner: BinaryReaderErrorInner { message: "reference types must be enabled", offset: 25, needed_hint: None } })
```

I think we may just need to enable ref types in the fuzz target's validator.

**Comment by fitzgen** [comment]
> I think we may just need to enable ref types in the fuzz target's validator.

Uh... we *are* enabling reference types in the validator:

```
[fuzz/fuzz_targets/mutate.rs:58] config.reference_types_enabled = true
[fuzz/fuzz_targets/mutate.rs:74] features.reference_types = true
[2021-12-03T18:04:55Z DEBUG mutate] validation result = Err(BinaryReaderError { inner: BinaryReaderErrorInner { message: "reference types must be enabled", offset: 25, needed_hint: None } })
```

**Comment by fitzgen** [comment]
I wonder if this is from a reader somewhere inside `wasm-mutate` rather than in the fuzz target itself?

**Comment by fitzgen** [comment]
cc @Jacarte

**Comment by Jacarte** [comment]
> I wonder if this is from a reader somewhere inside `wasm-mutate` rather than in the fuzz target itself?

Well, not according to the log. Is it after or before #407 ?

**Comment by fitzgen** [comment]
> Is it after or before #407 ?

After, see "commit 061f7dd" from the OP.
