### ISSUE TITLE
[feature request][wasmparser]duplicate import name should be allowed

### ISSUE THREAD

**Issue by PureWhiteWu** [bytecodealliance/wasm-tools#434]
According to the [wasm spec](https://webassembly.github.io/spec/core/syntax/modules.html#imports), import names can be the same:

> Unlike export names, import names are not necessarily unique. It is possible to import the same / pair multiple times; such imports may even have different type descriptions, including different kinds of entities. A module with such imports can still be instantiated depending on the specifics of how an embedder allows resolving and supplying imports. However, embedders are not required to support such overloading, and a WebAssembly module itself cannot implement an overloaded name.

Now wasmparser doesn't support this feature(so wasmtime doesn't either), but this is really necessary, especially for Go users.

The only available go compiler for wasm `tinygo` will generate code like this:

```
...
  (import "wasi_snapshot_preview1" "fd_write" (func $runtime.fd_write (type $t9)))
...
  (import "wasi_snapshot_preview1" "fd_write" (func $__imported_wasi_snapshot_preview1_fd_write (type $t9)))
...
```

And this results in error when using wasmtime:

```
$ wasmtime compile ...
Error: failed to parse WebAssembly module

Caused by:
    Invalid input WebAssembly code at offset 817: duplicate import name `wasi_snapshot_preview1::fd_write` already defined
```

I found that this is because `wasmparser` uses a set `NameSet` to storage imports.

I tried wasmer, it works fine, and here's their code: https://github.com/wasmerio/wasmer/blob/master/lib/types/src/module.rs#L80

Though the wasm spec also indicates that `embedders are not required to support such overloading`, I really hope wasmparser can support this.

**Comment by alexcrichton** [comment]
Can you share the code that you're using to validate? This error only happens when `module_linking` is enabled which is disabled by default (and the current implementation is known to have this "breaking change"). This should validate by default otherwise, though, unless module linking is enabled accidentally (and generally it shouldn't because it's still an experimental wasm proposal)

**Comment by PureWhiteWu** [comment]
Oh, I enabled all the features, that may be the problem.
Thank you very much!

**Comment by PureWhiteWu** [comment]
So this behaviour isn't compatible with module_linking? Will `module_linking` support it in the future?

**Comment by alexcrichton** [comment]
The current implementation of `module_linking` will be updated in the future to not have this breaking change, which means that in the future when all features are enabled this won't cause valid wasm today to become invalid. 

Given though that this is a known issue with the module linking proposal I'm going to close this issue, but thanks for the report!
