### ISSUE TITLE
wast: likely-confusing unicode character found '\u{202e}'

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#440]
I just updated the `wast` dependency from `38.0.1` to `39.0.0` for the `wasim` interpreter which causes the `names.wast` Wasm spec test to start failing with the message:

```
thread 'spec::v1::wasm_names' panicked at 'failed to create ParseBuffer for tests/spec/testsuite-v1/names.wast: likely-confusing unicode character found '\u{202e}'
     --> <anon>:112:22
      |
  112 |   (func (export "￯​ ­⁠ ") (result i32) (i32.const 40))
      |                      ^', tests/spec/v1/run.rs:24:23
```

We use the Wasm spec test suite from commit `0e7987e`.
I think this bug might have to do with a recent optimization for Wast because it changed some unicode handling code:
https://github.com/bytecodealliance/wasm-tools/pull/389
(just a guess though)

**Comment by alexcrichton** [comment]
This is working as intended, and for the spec tests you'll need to configure `lexer.allow_confusing_unicode` to allow this.

**Comment by Robbepop** [comment]
> 

Thanks a lot for the answer! I will try this out.
