### ISSUE TITLE
wasmparser: Return concrete type for BrTable::targets

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#459]
Currently `BrTable::targets` returns an [`impl Trait` type: `impl Iterator<Item = Result<u32>`](https://github.com/bytecodealliance/wasm-tools/blob/ac9028a4c52dbf1b0e78b24be33b7e5ce9618ca6/crates/wasmparser/src/binary_reader.rs#L1985).
This can be unflexible for user code, e.g. when user code wants to efficiently wrap the `BrTable` for a cleaner API in the client code.
However, with an `impl Trait` this is not really possible to my knowledge.

# Example

```rust
/// A thin-wrapper around a Wasm `br_table` construct.
///
/// # Note
///
/// This wrapper assumes that Wasm validation of the `br_table` has already
/// happened and therefore panics upon encountering errors instead of forwarding
/// those.
#[derive(Debug)]
pub struct WasmBrTable<'a> {
    /// The underlying inner `wasmparser` branching table.
    br_table: wasmparser::BrTable<'a>,
}

impl<'a> BrTable for WasmBrTable<'a> {
    type Targets = WasmBrTableTargets; // ERROR: missing generic argument

    fn len(&self) -> u32 {
        self.br_table.len()
    }

    fn is_empty(&self) -> bool {
        self.br_table.is_empty()
    }

    fn default(&self) -> RelativeDepth {
        RelativeDepth::from_u32(self.br_table.default())
    }

    fn targets(&self) -> Self::Targets {
        WasmBrTableTargets {
            iter: self.br_table.targets(),
        }
    }
}

/// Thin wrapper around the targets of a `br_table` coming from `wasmparser`.
///
/// # Note
///
/// This wrapper assumes that Wasm validation of the `br_table` has already
/// happened and therefore panics upon encountering errors instead of forwarding
/// those.
pub struct WasmBrTableTargets<T> {
    /// The underlying iterator of the target relative depths.
    iter: T,
}

impl<T> Iterator for WasmBrTableTargets<T>
where
    T: Iterator<Item = Result<u32, wasmparser::BinaryReaderError>>,
{
    type Item = RelativeDepth;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter
            .next()
            .map(|item| {
                item.unwrap_or_else(|error| {
                    panic!(
                        "encountered unexpected invalid relative depth of `br_table`: {}",
                        error
                    )
                })
            })
            .map(RelativeDepth::from_u32)
    }
}
```

Needless to say that this use case is currently impossible to implement with the current API of `wasmparser`.
Given that I want to keep the `BrTable` trait (for dependency inversion etc.) based API the next best thing a user code could do is to `collect` everything into a `Vec` which is a very unelegant solution and also not very efficient.

The solution is to return a concrete iterator type for `wasmparser`'s `BrTable::targets` method.

I'd happily create a PR for this if any of the `wasmparser` maintainers give me the :ok: .

**Comment by alexcrichton** [comment]
This seems fine by me to add, `impl Trait` is typically just used for convenience but it's fine to replace those with manual iterator implementations as necessary.
