### ISSUE TITLE
wasm-shrink not effectively shrinking straight-line code

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#511]
With the simd support in https://github.com/bytecodealliance/wasm-tools/pull/505 I was trying to shrink the reproduction test cases from https://github.com/bytecodealliance/wasmtime/issues/3951 as sourced from oss-fuzz to get something along the lines of the reproduction that I ended up getting to in the issue itself. One example original file was [e.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/8336023/e.wasm.gz) which when shrunk with:

```
$ cat test.sh
#!/bin/sh
$HOME/code/wasmtime/target/debug/wasmtime \
  compile --wasm-features memory64,multi-memory \
  --target x86_64 $1 -o /dev/null 2>&1 | \
  grep "register allocation: "
$ cargo run --release shrink ./test.sh e.wasm
    Finished release [optimized] target(s) in 0.05s
     Running `/home/acrichto/code/wasm-tools/target/release/wasm-tools shrink ./test.sh e.wasm`
4886 bytes (0.33% smaller)
4875 bytes (0.55% smaller)
4871 bytes (0.63% smaller)
4868 bytes (0.69% smaller)
4830 bytes (1.47% smaller)
4829 bytes (1.49% smaller)
4828 bytes (1.51% smaller)
4796 bytes (2.16% smaller)
4793 bytes (2.22% smaller)

e.shrunken.wasm :: 4793 bytes (2.22% smaller)
================================================================================
(module 
...
```

Here there reduction really didn't do anything at all unfortunately. The function itself is one giant basic block with a ton of simd-looking things in the middle. There aren't a lot of simd reduction rules but even the one we have that replaces v128 expressions with a const-0 should do something here. 

The reduction has a ton of `f64x2.nearest` instructions which is a unop that can simply be removed at any time in wasm, so I added a reduction rule:

```diff
diff --git a/crates/wasm-mutate/src/mutators/peephole/rules.rs b/crates/wasm-mutate/src/mutators/peephole/rules.rs
index b8f240a5..125fdb5f 100644
--- a/crates/wasm-mutate/src/mutators/peephole/rules.rs
+++ b/crates/wasm-mutate/src/mutators/peephole/rules.rs
@@ -579,6 +579,11 @@ impl PeepholeMutator {
             }
         }

+        rules.push(rewrite!(
+            "f64x2.nearest-remove";
+            "(f64x2.nearest ?x)" => "?x"
+        ));
+
         rules
     }
```

and it also didn't actually remove anything or make the final module any smaller.

@fitzgen do you know what might be going on here? I suspect that this is something related to how there's no tree-like AST representation of the input code, but I figured that wasm-mutate would still want to mutate some things but I could be wrong.

**Comment by alexcrichton** [comment]
Oh I should mention that this is using bytecodealliance/wasmtime@3bfbb3226e35c09f50ea936f7d603397a1bb5f86 which still has the original bug in question.

**Comment by alexcrichton** [comment]
I dug into this a little bit. One issue was https://github.com/bytecodealliance/wasm-tools/pull/513, and while that helps it's not the whole problem. I reduced this a bit manually to:

```wasm
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    (local i64 i64 externref i64 i64 i64 i32 i64 i64 i64 i64 i64)
    (i64.store16
      (i16x8.extract_lane_u 1
        (i16x8.sub
          (i8x16.gt_u
            (i8x16.gt_u
              ;; ===================================================
              ;; this expression can be replaced with v128.const 0
              ;; and the bug still reproduces
              (i16x8.max_s
                (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
                (i8x16.eq
                  (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
                  (i8x16.add_sat_s
                    (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
                    (v128.xor
                      (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
                      (v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000))
                  )
                )
              )
              ;; ===================================================
              (i64x2.neg
                (global.get 0))
            )
            (global.get 0)
          )
          (global.get 0)
        )
      )
      (i64.const 0)
    )
  )
  (memory (;0;) 271)
  (global (;0;) (mut v128) v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
)
```

Currently `wasm-smith` reduces this no further, but the expression I highlighted can be removed and replaced with a constant zero and the bug still reproduces in Wasmtime. My assumption was that [this rule](https://github.com/bytecodealliance/wasm-tools/blob/d11a2cbbb0b368d882f4682d31d8f3f561c03860/crates/wasm-mutate/src/mutators/peephole/rules.rs#L448-L452) would cover that use case, but it currently does not appear to. This is where I think my limited understanding of wasm-mutate and `egg`/etc has reached its limits and I'd have to dig further to try to understand what's going on and why the mutation isn't happening.

**Comment by fitzgen** [comment]
Taking a look...

**Comment by fitzgen** [comment]
Seeing a lot of stuff like this in the logs:

```
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 5
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 6
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 7
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 8
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 9
[2022-03-23T22:41:48Z WARN  wasm_mutate::mutators::peephole::dfg] wasm operator not implemented: V128Xor
[2022-03-23T22:41:48Z TRACE wasm_mutate::mutators::peephole] DFG cannot be constructed for opcode 10
[2022-03-23T22:41:48Z DEBUG wasm_mutate] mutator wasm_mutate::mutators::peephole::PeepholeMutator failed: There are not applicable mutations for the input Wasm module.; will try again
```

I think that 

1. we should add support for constructing the DFG from `v128.xor` instructions, obvisoulsy, and
2. we should support "stopping" the DFG at instructions we don't understand and treating the value as opaque the same as if they came from a load or were function parameters etc. This way we can still reduce the parts of the DFG that we do understand.

**Comment by fitzgen** [comment]
After adding `Lang` variants for `v128.xor` and a couple others that looked like there were missing, I get this:

```
big.shrunken.wasm :: 83 bytes (56.08% smaller)
================================================================================
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    (local i64 i64 externref i64 i64 i64 i32 i64 i64 i64 i64 i64)
    global.get 0
    global.get 0
    i8x16.gt_u
    global.get 0
    i16x8.sub
    i16x8.extract_lane_u 1
    i64.const 0
    i64.store16)
  (memory (;0;) 271)
  (global (;0;) (mut v128) v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000))
================================================================================
```
