### ISSUE TITLE
Component validation doesn't internally have the concept of a module instance type

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#534]
I was surprised that `instantiate_core_exports` returned a `TypeDef::Module` since that I thought would be used for module types, not module instance types, and then later [here](https://github.com/bytecodealliance/wasm-tools/blob/6e6b7024c8174976fff37fba5363d67f37a50b4e/crates/wasmparser/src/validator/component.rs#L1445-L1458) when looking up an instance it only looks for `TypeDef::Module`. I think that wasmparser needs to internally have a distinction between `Module` and `ModuleInstance` to correctly validate this since we can't instantiate a core wasm module with a module

cc @peterhuene

**Comment by alexcrichton** [comment]
Hm I think I'm tripping over myself and the namings, I'm confused about `TypeDef::Module` because that says "this is a module type" but I missed the `instances` array as part of the lookup. I'll close this and when I can test this with the text format I'll try to re-verify or something.

**Comment by peterhuene** [comment]
Yeah, this is an artifact of `TypeDef` not having a way of describe core module _instance_ types (as the proposal itself lacks module instance types) and instead only describes core module types. So internally `wasmparser` represents the former with the latter but only concerns itself with the module type's _exports_ as if it were an _instance_ type.

I'm also entirely onboard with any refactorings that makes this less messy.
