### ISSUE TITLE
components: Function imports are not type-checked

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#587]
Given this `*.wat`:

```wasm
(component
  (import "" (component $m
    (import "" (func))
  ))
  (import "i" (func $f (result string)))
  (instance $i (instantiate (component $m) (with "" (func $f))))
)
```

which dumps as 

```
  0x0 | 00 61 73 6d | version 65546 (Component)
      | 0a 00 01 00
  0x8 | 01 0c       | type section
  0xa | 01          | 1 count
  0xb | 4e 03 01 7f | [type 0] Component([Type(Interface(Primitive(Unit))), Type(Function(ComponentFuncType { params: [], result: Type(0) })), Import(ComponentImport { name: "", ty: 1 })])
      | 01 4c 00 00
      | 02 00 01
 0x16 | 02 03       | import section
 0x18 | 01          | 1 count
 0x19 | 00 00       | [component 0] ComponentImport { name: "", ty: 0 }
 0x1b | 01 05       | type section
 0x1d | 02          | 2 count
 0x1e | 72          | [type 1] Interface(Primitive(String))
 0x1f | 4c 00 01    | [type 2] Function(ComponentFuncType { params: [], result: Type(1) })
 0x22 | 02 04       | import section
 0x24 | 01          | 1 count
 0x25 | 01 69 02    | [func 0] ComponentImport { name: "i", ty: 2 }
 0x28 | 06 08       | instance section
 0x2a | 01          | 1 count
 0x2b | 00 01 00 01 | [instance 0] Component { index: 0, args: [ComponentArg { name: "", kind: Function(0) }] }
      | 00 03 00
```

this succeeds in validation but it should fail

cc @peterhuene

**Comment by peterhuene** [comment]
So I think that, based on the component model's subtyping rules, the first example above should actually pass validation as the return type of the argument is `string` which is indeed a subtype of the expected return type of `unit`.

It makes sense as the component `$m` doesn't need the returned value for its imported function.

The second example is indeed a bug where the subtyping rules for function types didn't check that the supertype didn't have fewer parameters than the subtype.

**Comment by alexcrichton** [comment]
Oh dear I did not realize that subtyping was implemented at the function level at this time.

Personally I'm so wary of subtyping at the function level I feel somewhat strongly that we should not implement it at this time until it's fleshed out more at the spec level. How would you feel about removing the subtyping for functions entirely?

**Comment by peterhuene** [comment]
I merged the fix to correct the subtype check. I think we should raise an issue with the spec if we haven't done so already; I know it's on Luke's plate to better flesh out the subtype checking rules.

That said, I think subtype checking on function types is going to be necessary for the back-compat story of the component model, though.

I'd prefer to leave as-is in wasmparser for now so that it's compatible with the spec since it's a low-level crate and perhaps we impose an equality check limitation in wasmtime's implementation for now?

**Comment by alexcrichton** [comment]
To me though this has very serious implications for the implementation in Wasmtime. I was not aware that not only was subtyping of arguments on the horizon but even subtyping of the number of function parameters and results. This throws into question the entire design we've got for calling component functions if we're required to handle subtyping as well...

I... will try to figure out what to do with this.
