### ISSUE TITLE
`wasm-smith`: Prefer writing values to memory instead of `drop`ing them

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasm-tools#655]
When we `drop` them, then the Wasm engine can do DCE and ignore lots of code.

If we have a non-empty memory, we can write to the first page. Maybe even do a bump allocation thing where first we write to offset 0, then 1, etc. This way an alias analysis won't trivially see through this stuff and make a bunch of expressions DCE'd again.

Could be a post-pass method on `Module` that rewrites `drop`s or it could be done in `CodeBuilder` directly.

**Comment by abrown** [comment]
The way I am thinking about this right now: what if we added `Config::orphaned_stack_values()` and allowed it to be configured with,

```rust
/// What to do with values left on the stack when running out of randomness when generating the function.
enum OrphanedValueAction {
  /// Drop any orphaned values in the function; this is the default.
  Drop,
  ///  Store the orphaned values in memory, or fail if a memory is not present.
  StoreMemory,
  /// Adjust the function type, adding return types for any remaining values remaining on the stack.
  AdjustFuncType
}
```
The issue with `AdjustFuncType` is that we've already generated the `FuncType` by the time the `CodeBuilder` is emitting instructions but perhaps it wouldn't be impossible to modify it (or add the type lazily?). The issue with `StoreMemory` is that we don't always know if we have a memory; I think the easiest thing to do here is just fail. What do you think of this kind of configuration?
