### ISSUE TITLE
wasmparser: Improve performance by avoiding unpredictable branches

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#695]
While working on `wasmi` I found that overhead from parsing and validating Wasm bytecode is quite significant using `wasmparser`.
My suspicion is that a significant part of this overhead is due to numerous unpredictable branches given the `wasmparser` API for Wasm operator parsing. It is of importance that this part of the `wasmparser` crate is really efficient given that every Wasm execution requires to parse and validate all Wasm operators which make up the greatest part of the Wasm file usually.

## Current API

Currently `wasmi` does roughly the following in order to parse, validate and translate Wasm operators to its internal `wasmi` bytecode:
```rust
    /// Parses and validates the Wasm operators and translate them to `wasmi` bytecode.
    fn translate_operators(&mut self) -> Result<()> {
        let mut reader = self.func_body.get_operators_reader()?;
        while !reader.eof() {
            let (operator, offset) = reader.read_with_offset()?;
            self.validator.op(offset, &operator)?; // #1
            self.translate_operator(operator)?; // #2
        }
        reader.ensure_end()?;
        self.validator.finish(reader.original_position())?;
        Ok(())
    }
```
This might be similar for other users of the `wasmparser` crate given its API.

## The Problem

I marked 2 lines with `// #1` and `// #2`. Those two lines are were the unpredictable branches mostly happen due to matching on the `Operator` variant.
With a different interface we could get rid of both unpredictable branches. One solution is to introduce a trait `VisitOperator` that has a visitor-like method for each `Operator` variant with its variants fields as method parameters and an `offset` field given that `read_with_offset` returns a pair of `(offset: u32, op: Operator)`.
This way we could add a new API for the [`OperatorsReader`](https://docs.rs/wasmparser/0.88.0/wasmparser/struct.OperatorsReader.html) to visit the next `Operator` given some visitor. Furthermore we could add another API to also `validate_and_visit` the next `Operator`. Internally the `OperatorsReader` knows which `Operator` to visit next and directly calling the proper method of the new `VisitOperator` trait. Interestingly the `wasmparser::Validator` could just implement the very same trait as users would do in order to be able to visit each `Operator` efficiently.

## Backwards Compat

This proposal should not break backwards compat since we are just adding a new API and do not plan to change existing ones.
I plan to research about the gains in the `wasmparser-nostd` fork but I already conducted similar optimizations elsewhere in `wasmi` and received significant gains.

## Proposal Downsides

The major downside is that this `VisitOperator` trait is going to be huge. In fact I would propose to generate it via Rust proc macros given the `Operator` `enum`. Another obstacle is that we somehow have to embed user errors that might arise from the `VisitOperator` calls back to the caller of the new API.

## Proposal Example

I imagine this `VisitOperator` trait to look roughly like:
```rust
pub trait VisitOperator {
    type Output;

    fn visit_unreachable(&mut self, offset: u32) -> Self::Output;
    fn visit_nop(&mut self, offset: u32) -> Self::Output;
    fn visit_block(&mut self, offset: u32, ty: BlockType) -> Self::Output;
    fn visit_loop(&mut self, offset: u32, ty: BlockType) -> Self::Output;
    fn visit_if(&mut self, offset: u32, ty: BlockType) -> Self::Output;
    fn visit_else(&mut self, offset: u32) -> Self::Output;
    fn visit_br(&mut self, offset: u32, relative_depth: u32) -> Self::Output;
    etc.
}
```

With all this said the above example code would roughly look like this:

```rust
    /// Parses and validates the Wasm operators and translate them to `wasmi` bytecode.
    fn translate_operators(&mut self) -> Result<()> {
        let mut reader = self.func_body.get_operators_reader()?;
        while !reader.eof() {
            reader.visit_next_operator(&mut self.translator)?;
        }
        reader.ensure_end()?;
        self.validator.finish(reader.original_position())?;
        Ok(())
    }
```
Example impl of `self.translator`:
```rust
struct FuncTranslator {
    validator: wasmparser::FuncValidator<wasmparser::ValidatorResources>,
    codegen: FuncCodegen,
}

impl VisitOperator for FuncTranslator {
    type Output = Result<(), TranslateError>;

    fn visit_unreachable(&mut self, offset: u32) -> Self::Output {
        self.validator.visit_unreachable(offset)?;
        self.codegen.visit_unreachable(offset)?;
        Ok(())
    }

    fn visit_nop(mut self, offset: u32) -> Self::Output {
        self.validator.visit_nop(offset)?;
        self.codegen.visit_nop(offset)?;
        Ok(())
    }

    etc...
}
```
What do you think about this new API?

**Comment by alexcrichton** [comment]
Personally I think it'd be great to make wasmparser more suitable for extremely fast validation/parsing approaches. Right now as you've found I don't think it's in the best place. Another slow part of wasmparser's API is https://github.com/bytecodealliance/wasm-tools/issues/188 although I suspect that the operator decoding/validation is probably the slowest part for most real-world modules.

I think the API you've proposed here is quite reasonable. I additionally wish there were a better way around this than having a very large trait but I'm not sure of one myself. Currently though there's three matches where (1) happens when the opcode is originally read from the input, (2) happens during validation and a match on `Operator`, and (3) happens in the embedder when it performs translation. I think (1) is unavoidable but the API you've proposed here should remove the rest.

Also there's no need to worry about backwards compatibility with this crate. We care about usability but otherwise new major versions are released frequently so a breaking change is not a problem.

**Comment by alexcrichton** [comment]
One thing I'd also ideally like to do one day is to have some sort of textual/macro-based description of all instructions which could be used to generate traits like this, but that's fine to defer to another day.

**Comment by Robbepop** [comment]
I'd be willing to implement the proposed API and see how it improves performance given our benchmarks if you are okay.

> One thing I'd also ideally like to do one day is to have some sort of textual/macro-based description of all instructions which could be used to generate traits like this, but that's fine to defer to another day.

I am sure we could combine this work.

**Comment by alexcrichton** [comment]
Sure yeah, I'm happy to help review! 

For now I'm thinking `macro_rules!` to keep the `wasmparser` crate at least semi-slim, but if it really helps I think going a full proc-macro could be considered too

**Comment by alexcrichton** [comment]
I should mention one of the main benefits to procedurally generating this trait is that there's arguably a ton of locations in this codebase that every single wasm instruction is mentioned, and somehow deduplicating all that would be nice. I don't think there's a ton of benefit in deduplicating a handful of blocks simply in `wasmparser`, the main benefit as I see it is deduplicating all the matches in all the crates. That's a pretty big thing to take on though so I don't think it's worth doing just yet.

**Comment by Robbepop** [comment]
> Sure yeah, I'm happy to help review!
> 
> For now I'm thinking `macro_rules!` to keep the `wasmparser` crate at least semi-slim, but if it really helps I think going a full proc-macro could be considered too

I agree it is a trade-off. I'd also prefer a `macro_rules` for its simplificty and compilation times. However, I suppose an attribute proc. macro would be most future proof for our requirements. Unlike with `macro_rules` we could derive `snake_case` trait method names from the camel case `enum` variant identifiers etc. and with regards to maintenance there are thereby fewer things that could go wrong, e.g. misspelling an identifier.

> I should mention one of the main benefits to procedurally generating this trait is that there's arguably a ton of locations in this codebase that every single wasm instruction is mentioned, and somehow deduplicating all that would be nice. I don't think there's a ton of benefit in deduplicating a handful of blocks simply in wasmparser, the main benefit as I see it is deduplicating all the matches in all the crates. That's a pretty big thing to take on though so I don't think it's worth doing just yet.

Please correct me if I understood wrong. Are you proposing a proc. macro approach to define all the (similar) definitions in a single crate where all the other `wasm-tools` crates could depend on?

**Comment by alexcrichton** [comment]
That's sort of what I'm thinking yeah. But to be clear I've not planned out what this proc macro would look like ahead of time so I don't know if it's even possible. I'm mostly pointing out that `wasmparser` isn't in an island and there's a number of other crates in this repository that also enumerate all the instructions. Having these giant `match` statements isn't really the end of the world but if you're looking to unify some of them it might be good to look at the rest of the crates as well instead of just `wasmparser`.

Again though I think it's fine to do whatever here to start out with and it can be tweaked over time.

**Comment by Robbepop** [comment]
@alexcrichton I am done with the work on this issue in [this PR](https://github.com/bytecodealliance/wasm-tools/pull/697). Happily waiting for a review. The changes required more code than I expected but besides that the PR is pretty self contained. Initial benchmarks show roughly 10% improvement for the internal case where we only had 1 unpredicted branch. So the speed-ups for user code with 2 unpredicted branches is probably even better.
