### ISSUE TITLE
Parse from `R: Read` instead of byte slice

### ISSUE THREAD

**Issue by Vurich** [bytecodealliance/wasm-tools#7]
Even though this parser is streaming, it's currently not possible to actually have it operate on a stream. The API requires a `&[u8]`. This isn't really necessary though, most of the API could remain identical while supporting any input type `R where R: Read`. I tried to implement this myself but this codebase is so huge and has so much duplicated code that I gave up, since it's not immediately necessary for my use-case.

**Comment by alexcrichton** [comment]
I've proposed a redesign of this crate which would make it possible to implement this feature at https://github.com/bytecodealliance/wasm-tools/pull/40, and if others have feedback on that it'd be very much appreciated!

**Comment by Robbepop** [comment]
Since #40 has been merged, what is left to implement this?

**Comment by alexcrichton** [comment]
Ah yes indeed I don't think there's a ton left to do on this. The [docs have an example](https://docs.rs/wasmparser/0.66.0/wasmparser/struct.Parser.html#method.parse) of parsing from `T: Read`, and perhaps that's good enough?

**Comment by Robbepop** [comment]
Discoverability of the docs could be better but I think this docs and updated codebase in place this issue is pretty much implemented and can be closed.
