### ISSUE TITLE
`wasm-compose`: error when trying to compose example backend

### ISSUE THREAD

**Issue by font** [bytecodealliance/wasm-tools#722]
In the following step:

https://github.com/bytecodealliance/wasm-tools/blob/a36144e6ecc09bcfa619369c132de882c625811b/crates/wasm-compose/example/README.md?plain=1#L161

I am getting the following error:

```shell
→ wasm-tools compose
Error: failed to parse component `../backend/target/wasm32-unknown-unknown/release/backend.wasm`

Caused by:
    0: failed to validate WebAssembly component `../backend/target/wasm32-unknown-unknown/release/backend.wasm`
    1: unexpected end-of-file (at offset 0x4f)
```

Is this example expected to work given the current state of `wasm-compose`?

**Comment by alexcrichton** [comment]
cc @peterhuene

**Comment by peterhuene** [comment]
I believe this to be a incongruity between current `wasm-tools` and `cargo-component` (and by extension `wit-component`).

Current `wasm-tools` has been updated to a "newer" component model binary format, whereas I'm still waiting on `wit-parser` changes to be able to update `wit-component` (and by extension `cargo-component`) to the new format.

@font if you checkout the commit before 63f8ab39d93925fd3463236814128de23fc3ac5e in `wasm-tools`, are you able to reproduce the problem?

**Comment by font** [comment]
> I believe this to be a incongruity between current `wasm-tools` and `cargo-component` (and by extension `wit-component`).
> 
> Current `wasm-tools` has been updated to a "newer" component model binary format, whereas I'm still waiting on `wit-parser` changes to be able to update `wit-component` (and by extension `cargo-component`) to the new format.
> 
> @font if you checkout the commit before [63f8ab3](https://github.com/bytecodealliance/wasm-tools/commit/63f8ab39d93925fd3463236814128de23fc3ac5e) in `wasm-tools`, are you able to reproduce the problem?

@peterhuene that was it, thank you!
