### ISSUE TITLE
`wasmparser`: Add API to access FuncValidator state

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#732]
## The Problem

When using the `wasmparser` crate for Wasm parsing and validation currently users have to mirror certain structures in some use cases.
Therefore this work is duplicated and could easily be deduplicated by making the `wasmparser` crate offer an API to access its internal state.
For example in `wasmi` we mirror the value stack and the way we register local variables in order to translate Wasm to `wasmi` bytecode.

The new `VisitOperator` API allows to interweave the validator into the user code very flexibly.

## Example API

- `fn len_locals(&self) -> u32;`: Returns the number of registered local variables.
- `fn len_params(&self) -> u32;`: Returns the number of paramters of the function.
- `fn len_results(&self) -> u32;`: Returns the number of results of the function.
- `fn get_local(&self, index: u32) -> Option<ValType>;`: Returns the type of the local variable at the given index.
- `fn get_value_nth_back(&self, index: u32) -> Option<ValType>;`: Returns the value type of the n-th value from the value stack from the back where an index of 0 is the last value.
- `fn len_values(&self) -> u32;`: Returns the current height of the value stack.

Combined with the new `VisitOperator` API this allows user code to rely on the `wasmparser` validator without duplicating the logic to sync the state properly.

## Alternative: Return Result

Usually accesses to the state need to be performed before validation since validation would cause the state to change. Therefore it might be useful to not return `Option<ValType>` for `get_local` and `get_value_nth_back` but instead return a validation `Result`. This means that validation was partly driven by the user code though.

## Alternative: Peek Validation

An alternative is to have a `peek_validate` API that validates the Wasm operator while not changing the validator state but returning a `ValidatorStateTransfer` "object" instead that applies the required state transitions in the validator later via another API called by the user.

## Future Work

We could do the same for the control stack but that is a bit trickier since it usually carries information specialized to its task, e.g. different information requirements for validation and translation. So for now I would not include the control stack into the initial API but we may introduce such an API at later stages.

**Comment by alexcrichton** [comment]
I think this would be a great idea to add! I like the idea of adding accessors for the information already there as opposed to adding new functionality like `peek_validate`.

**Comment by Robbepop** [comment]
Cool, I will prepare a PR for this then. :)
