### ISSUE TITLE
Data segments double-counted when data count section present

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/wasm-tools#756]
I have a Wasm module with 53,984 data segments, which is less than the current value of `MAX_WASM_DATA_SEGMENTS`, which is 100,000.  However, validation fails with the error "data segments count exceeds limit of 100000".

Curious, I dug into the code in validator.rs and found that `Validator::data_count_section` sets `Module::data_count` to the number of data segments (53,984).  Later, though, `Validator::data_section` ends up calling `check_max` with arguments that indicate an additional 53,984 data segments are being added, totaling 107,968, even though both counts refer to the same set of data segments.

I think either `data_cont_section` or `data_section` need to be changed to avoid this double counting, but I'm not sure which or how, so I'd appreciate any guidance.

**Comment by peterhuene** [comment]
I think the `cur_len` argument for `check_max` here should simply be `0`.

We're already ensuring the section isn't parsed multiple times and later on we validate the the segment count matches what was specified in the data count section, so this check should simply ensure that `count` does not exceed `MAX_WASM_DATA_SEGMENTS`.

**Comment by dicej** [comment]
Thanks, @peterhuene.  Please see #759 for the fix.
