### ISSUE TITLE
why bulkmemory in wasmparser have 12 instrs, but in spec i only see 7 instrs

### ISSUE THREAD

**Issue by hunjixin** [bytecodealliance/wasm-tools#781]
code:
```rs
            @bulk_memory MemoryInit { segment: u32, mem: u32 } => visit_memory_init
            @bulk_memory DataDrop { segment: u32 } => visit_data_drop
            @bulk_memory MemoryCopy { dst: u32, src: u32 } => visit_memory_copy
            @bulk_memory MemoryFill { mem: u32 } => visit_memory_fill
            @bulk_memory TableInit { segment: u32, table: u32 } => visit_table_init
            @bulk_memory ElemDrop { segment: u32 } => visit_elem_drop
            @bulk_memory TableCopy { dst_table: u32, src_table: u32 } => visit_table_copy
            @bulk_memory TableFill { table: u32 } => visit_table_fill
            @bulk_memory TableGet { table: u32 } => visit_table_get
            @bulk_memory TableSet { table: u32 } => visit_table_set
            @bulk_memory TableGrow { table: u32 } => visit_table_grow
            @bulk_memory TableSize { table: u32 } => visit_table_size
```

spec:
![image](https://user-images.githubusercontent.com/41407352/193537258-154ec24b-11ff-41aa-8c31-ccefa3054ae0.png)

**Comment by alexcrichton** [comment]
I believe this is probably just a mistake, if you'd like to send a PR feel free!

That being said I personally feel like the line between the bulk memory and reference types proposal is quite blurry, so I think that it probably doesn't make sense to enable one without the other. Additionally if these are changed I think the validator would also need to change to require a different proposal (if you're interested in flipping bits on proposals).

**Comment by Robbepop** [comment]
Indeed some of those instruction should have been marked as `@reference_types` instead.
