### ISSUE TITLE
How to read a section at a time using wasmparser?

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasm-tools#784]
The object crate needs this (I have been trying to update it to the latest wasmparser version). The `Payload` type is not suitable as it splits certain sections, like the code section, into multiple parts. It also doesn't allow getting the `SectionCode` and for getting the section range you have to match on all possible sections rather than calling a single method.

**Comment by alexcrichton** [comment]
With `Payload::as_section` I believe this is now largely done, and an example is [here](https://github.com/bytecodealliance/wasm-tools/blob/30949232738f3610bcd390f19e81e00995ef2bb8/src/bin/wasm-tools/strip.rs#L50-L67)
