### ISSUE TITLE
Valid Wasm module fails validation

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasm-tools#79]
[test.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/5096780/test.wasm.gz)

```wat
(module
  (type (;0;) (func))
  (type (;1;) (func))
  (import "" "" (global (;0;) (mut i32)))
  (func (;0;) (type 1)
    (local f64)
    loop  ;; label = @1
      loop  ;; label = @2
        unreachable
        global.get 0
        global.get 0
        br_if 0 (;@2;)
        global.set 0
        unreachable
      end
      unreachable
    end
    unreachable))
```

I need to double check the spec and how unreachable code is validated, but all of `wasm2wat`, `wasm-validate`, and `wasm-dis` accept this module as valid, while `wasmparser`'s validator returns an error.

**Comment by fitzgen** [comment]
It looks like our handling of `br_if` is accidentally un-setting the stack polymorphic bit on the block here.

**Comment by yurydelendik** [comment]
Tried #29c41f2 , fails at

https://github.com/WebAssembly/testsuite/blob/645d8fcf9cab495cfc8f3772a2318480d646b43e/unreached-invalid.wast#L689-L709
