### ISSUE TITLE
`VisitOperator`: don’t bake in `offset` into visit methods

### ISSUE THREAD

**Issue by nagisa** [bytecodealliance/wasm-tools#803]
Today each `VisitOperator` method takes the binary input offset as an argument, like so:

```
fn visit_nop(&mut self, offset: usize) -> Self::Output;
```

I’d like to argue that this is probably overly onerous approach to passing this information through, not to mention, this also inhibits expanding to passing through future information. Let me decompose both and suggest a solution.

Consider a visitor implementation, one in which the offset is currently ignored and many methods delegate to some common implementation of something (which is going to be the case for many visitors – a number of WASM operators are categorized into groups of very similar behaviour):

```
fn visit_*(&mut self, _: usize, *) -> Self::Output {
    self.do_some_things(...)?;
    Ok(())
}
```

Now, turns out the errors that come out of `do_some_things` are utterly indecipherable, and so I would love to add some offset information to at least have a clue what area of the module parsed is causing issues.

With the current design, this will involve threading `offset` manually through all the layers of everything. There isn’t a nice single place to actually set this information.

Now imagine `wasmparser` starts wanting to expose some _more_ information while it is parsing the operands. I have no idea what that information might be yet, but what I’m sure of, is that adding another argument will not fly. At all.

Since all visitors will inevitably be a custom type implementing the `VisitOperator` trait, these types are already a great place to store some information, including the `offset` of the current instruction. With the way visitor is driven today this can be very straightforward to include:

```
let operators = function.get_operators_reader()?;
// Perfect place to obtain contextual information.
visitor.offset = operators.original_position(); // already exists!
operators.visit(&mut visitor)?;
```

For users who don’t care about the offset, now it is very straightforward to ignore, and once they do start caring about it, threading this information to their visitor is quite simple too. Any future additional context can be exposed in much the same way without adjusting all 500-something methods in the visitor.

Question is: does everybody else share the same amount of enthusiasm for removing the `offset` parameter from the `VisitOperator` methods? I’m happy to prep a PR ^^

**Comment by alexcrichton** [comment]
This sounds reasonable to me, and I would agree that with my experience so far using the trait not having the `offset: usize` argument and storing it instead in context would help ergonomics a good deal. If you'd like to prep a PR that seems reasonable to me

**Comment by alexcrichton** [comment]
Resolved by https://github.com/bytecodealliance/wasm-tools/pull/804
