### ISSUE TITLE
Another valid modules fails validation

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasm-tools#83]
[test.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/5104147/test.wasm.gz)

```wasm
(module
  (type (func))
  (type (func (result f64 i32)))
  (func (type 1)
    loop
      br 0
      call 0
      br_if 0
      i32.trunc_f64_u
      unreachable
    end
    unreachable
  )
)
```

Haven't started investigating yet, but it looks pretty similar to the last one: unreachable code (following the unconditional `br`) and a `br_if` instruction.

cc @yurydelendik

**Comment by yurydelendik** [comment]
I cannot reproduce atm. It requires `--enable-multi-value` with "wasm-validate-rs" and looks like it is passing in wabt's "wasm-validate".

**Comment by fitzgen** [comment]
Ah woops, I translated the example to wat by hand wrong, here is the correct stuff:

[test.wasm.gz](https://github.com/bytecodealliance/wasm-tools/files/5104239/test.wasm.gz)

```wasm
(module
  (type (;0;) (func))
  (type (;1;) (func (result f64 i32)))
  (func (;0;) (type 1) (result f64 i32)
    loop (result f64 i32)  ;; label = @1
      br 0 (;@1;)
      call 0
      br_if 0 (;@1;)
      i32.trunc_f64_u
      unreachable
    end
    unreachable))
```

**Comment by fitzgen** [comment]
I get

```
Error: stack operand type mismatch (at offset 84)
```

Sorry for uploading the wrong wat!

**Comment by fitzgen** [comment]
(with `--enable-multi-value`)
