### ISSUE TITLE
Attach doc-comments to a WIT file

### ISSUE THREAD

**Issue by Michael-F-Bryan** [bytecodealliance/wasm-tools#836]
At the moment, you can add doc-comments to any item in a WIT file and the text will appear in the generated code as doc-comments for your target language, however it doesn't look like you can document the WIT file itself.

The idea is that users could write the following `guest.wit` file:

```
//! Functionality exposed by the guest.

/// A function that is called when the WebAssembly module is loaded.
on-load: function()
```

(I'm borrowing the `//!` syntax from Rust but don't have any particular preference)

Generating import bindings with `wit-bindgen wasmtime --import guest.wit` might then look like this:

```rust
pub mod guest {
  //! Functionality exposed by the guest.

  pub struct Guest<T> { ... }

  impl<T> Guest<T> {
    /// A function that is called when the WebAssembly module is loaded.
    pub fn on_load(&self, ...)-> Result<(), wasmtime::Trap> { ... }
  }
}
```

---

Concretely, supporting doc-comments for the WIT file itself will probably involve:

- Decide on a syntax (e.g. `//! ...` or `/// ...` with a newline separating it from the first item in the file)
- Add a `docs: Docs` field to `wit_parser::Interface` and update the parser to populate it
- Update each of the code generators to emit the appropriate doc-comments

**Comment by lann** [comment]
Now that there is a `package` item, would it make sense to reframe this issue as "support doc-comments on packages"?

**Comment by alexcrichton** [comment]
Sounds reasonable to me yeah!

**Comment by lann** [comment]
How should we handle package doc-comments in multiple files? Reasonable options seem like:

- Validation error (like mismatched package names)
- Silently drop all but one
- Concatenate

Making it an error seems...aggressive...but given that we don't define a parse order for multiple files the other options would be nondeterministic.

**Comment by alexcrichton** [comment]
Personally I'm always a fan of starting conservatively so I think a validation error is ok for now and if that becomes problematic we can work with that at the time and figure something else out.
