### ISSUE TITLE
Block names for `br` are not preserved

### ISSUE THREAD

**Issue by d3lm** [bytecodealliance/wasm-tools#841]
When parsing WAT into bytes and re-printing it then I have noticed that for blocks the name for the block itself preserved but not for `br` instructions for instance, e.g.
```
block $myBlock
  br $myBlock
end
```
When parsing and printing it again it produces:
```
block $myBlock ;; label = @1 
  br 0 (;@1;)
end
```
Is this a bug or on purpose, or can we change this so that the blocks use the name if it has one?

**Comment by alexcrichton** [comment]
Just an oversight, would be great to have this implemented!
