### ISSUE TITLE
unexpected end-of-file (at offset 0x1e18f7)

### ISSUE THREAD

**Issue by JensGM** [bytecodealliance/wasm-tools#842]
Hey,

When running `wasm-tools component new -o out.wasm in.wasm`, I'm struggling to generate bindings on other platforms than mac. On mac it's fine, but on both linux and windows I get:

```
Error: failed to parse the input component

Caused by:
    unexpected end-of-file (at offset 0x1e18f7)
```

**Comment by alexcrichton** [comment]
Thanks for the report but this is likely due to a recent change in the binary format. Can you confirm that the platforms you're testing all have the same version of `wasm-tools` and/or the producer toolchain?

**Comment by JensGM** [comment]
Hey, I managed to resolve it by removing a pinned version for wasm-tools, it likely just worked by luck on mac. Closing this issue. After updating I do however fail to generate bindings for python using python3 -m wasmtime.bindgen with an error:

```
RuntimeError: failed to extract interface information from component

Caused by:
    invalid leading byte (0x3) for component external kind (at offset 0x1e0d4f)
```

Is this due to the format change? (newest wasmtime for python)
