### ISSUE TITLE
Improve README.

### ISSUE THREAD

**Issue by mbebenita** [bytecodealliance/wasm-tools#9]
The intro README for this project doesn't say much. It would be great if we highlighted some of the performance and flexibility features of this parser, and why people should use it.

- [x] Highlight performance features.
- [ ] Highlight that it's flexible and can be used in a streaming fashion, describe why this is important and why this architectural decision was made.
- [ ] Give more context around the example, perhaps show the output of the example code.
- [ ] Highlight that it is well tested, and that it is used as part of the Cretonne project.
- [ ] Maybe draw a figure that describes the architecture.

**Comment by alexcrichton** [comment]
This is a pretty old issue at this point (7 years!), and times change and organizations and such. I think that the purpose of this issue has since moved on, so I'm going to close this.
