### ISSUE TITLE
`WasmFeatures::floats = false` allows using float types in parameters and locals

### ISSUE THREAD

**Issue by athei** [bytecodealliance/wasm-tools#909]
Examples of code that is successfully validated even if `floats: false`:

```wat
(module
	(func $foo (local f32)
		local.get 0
		drop
	)
)

(module
	(func $foo (param f32)
		local.get 0
		drop
	)
)
```

I think wasmparser only scans for specific instructions and doesn't check types.

**Comment by Robbepop** [comment]
The docs [`float` config] in the `WasmFeatures` type state that this only disallows Wasm operations on `f32` and `f64` types:
https://docs.rs/wasmparser/0.99.0/wasmparser/struct.WasmFeatures.html#structfield.floats

**Comment by athei** [comment]
Isn't `local.get` an operator on `f32` if the local is of that type?

**Comment by alexcrichton** [comment]
Personally I think it's reasonable to gate even locals of the type `f32` and `f64` when `floats` is disabled. I'm ok considering this a bug that can be fixed.

**Comment by Robbepop** [comment]
I actually get your point @alexcrichton since `local.get` of a `f32` or `f64` value probably won't introduce non-determinism. Only actual float instructions do. Even if you completely want to avoid non-deterministic behavior it is completely fine to pass around float values in various ways as long as you perform no non-deterministic operations on them.

**Comment by Robbepop** [comment]
@athei and me were just having a chat about this and had the following agreements:

1) We feel a little uneasy with the relaxation of the `floats` feature allowing float locals and basically allowing to pass around float values.
2) Given 1) we still feel like the `floats` feature as implemented by `wasmparser` would suffice our needs.

But I see your point in that a feature that is called `floats` should probably disable floats entirely (also types).

I personally am fine with either direction that you prefer for the `wasmparser` crate, @alexcrichton .

@athei what is your personal stance on this?

**Comment by athei** [comment]
> So given all that I would ask, is there a use case for disallowing float instructions but allowing float locals? 

No.  I don't see a use case for that. 

> If not I think that this issue should be resolved by rejecting f32 and f64 types in the validator.

Yes. This is why I made this issue. I want it to also reject wasm types.
