### ISSUE TITLE
Expose internals of wast::Error

### ISSUE THREAD

**Issue by darinmorrison** [bytecodealliance/wasm-tools#94]
I am interested in using `wast` in one of my projects for reporting parse errors. I need to be able to extract useful information about the errors such as the file name, span, error message, etc. But it seems I can only really get access to the displayed string with `wast` because all of the internals of [wast::Error](https://docs.rs/wast/23.0.0/wast/struct.Error.html) are private.

Is there any particular reason for this? Can it be changed?

In theory I could reparse the displayed string to collect this info but that's messy and error prone and I'd rather avoid going that route.

**Comment by alexcrichton** [comment]
This is done to keep the API stable over time, exposing minimal details and only adding accessors when required. There's no inherent reason to not export items, and if you'd like to get at some internal information feel free to send a PR!
