### ISSUE TITLE
failed to parse export section, effective type size too large

### ISSUE THREAD

**Issue by Finfalter** [bytecodealliance/wasm-tools#940]
A custom generator generates functions (in Rust) in order to put them in a WASI module. All functions must be visible from the outside and, thus, shall be exported. In order to do so, the Rust code is accompanied by a corresponding .wit file. The code is built by 
```bash
cargo wasi build --release
```

**Given the number of exported functions exceeds a certain threshold (~20,000), I get the following error:**
```
error: failed to process wasm at ../my_module.rustc.wasm

Caused by:
    failed to parse export section

Caused by:
    effective type size too large (at offset 911791)`
```
Is there a limit for _**type size**_? 
What is the limit? 
Can I increase it?

**Comment by alexcrichton** [comment]
The "type size" is a ceiling on an internal calculation in wasmparser for roughly how "big" the type of a wasm module is. For example if you have 20k exported functions that's at least 20k units of "size" where the function parameters/results are also additions to the size (which is probably why your module is [exceeding the 100k limit](https://github.com/bytecodealliance/wasm-tools/blob/4ee705fbb5600ae51ec3192b5a1cbf8f67bfda95/crates/wasmparser/src/limits.rs#L53)).

The limit here can't currently be increased at runtime, it's a compile-time limit. There's not a strong reason for it to be a compile time limit, however, and we could update it to being a runtime limit (but threading it down from all embedders could get quite tricky). I think it's probably reasonable to increase the limit, however, as it's currently arbitrarily chosen and wasn't meticulously picked or anything like that.

Would you be able to share your wasm module for reference as well?

**Comment by Finfalter** [comment]
Thank you for your thorough explanation. That leaves me with the option to set **_MAX_WASM_TYPE_SIZE_** and compile **wasm-tools** myself, right? Unfortunately, the module is about proprietary code which I am not allowed to share.

**Comment by alexcrichton** [comment]
Yes editing that should, I think, fix your use case here. I'll reiterate though that the current 100k value is completely arbitrary and I think would be fine to increase. If you're able to describe more about your use case though that would help with evaluating whether that's the best strategy here or whether there's a better alternative (such as changing type size calculations).

For example:

* Do all your functions have the same signature? If so what is it? If not what are the "top 5" function signatures used?
* Is this a core wasm module within a component or a standalone core wasm module having nothing to do with the component model?
* Is this module exported or imported? Or does it simply reside within a component?

**Comment by Finfalter** [comment]
Good idea to analyze the use case, here we go:

The kind of functionality is a decoder. Each function is able to extract a "signal" from a given stream of bytes. The logic for each function is unique but the type of result is mostly the same. Therefore, >98% of all functions share the same signature:
```wit
func(v0: list<u8>) -> tuple<float64, string, string>
```

The module exports functionality. So, I guess, in your terms the module is imported.

I am not too sure about the other terms. My guess is that it is a core wasm module within a component. To double check, I will describe how I craft this kind of module (there is a multitude of them): Ordinary Rust code is built with 
```cargo wasi build --release```.

The overall requirements are the following:
There are multiple use-cases for the decoder. Half of them are for the backend, the other half with direct user interaction. Some would want a Python environment, others the JVM. There is also a potential use-case for Javascript and the browser. Also, speed matters. There is lots of data to be processed. Maybe, the parameter type will change from vector to pointer eventually (this is not possible in a **.wit**, right?). For the moment, the software is a prototype but it is driven by a real-world business case.

Does that help you? Also, if you have any further thoughts and/or recommendations, I am happy to listen.

**Comment by alexcrichton** [comment]
Ok thanks! I'll try to poke around with this and see if I can't come up with a better solution for this.

**Comment by Finfalter** [comment]
Are you open for a few mor thoughts and questions regarding this topic?

In theorie, I have quite a few of the components mentioned above. The biggest would have to comprise ~45K functions of the kind described above. Do you think it is possible to set the defaults such that this is possible?

Also, what exactly adds to **_MAX_WASM_TYPE_SIZE_**, only exposed functionality like imported exported functions or all defined functions and types? I ask because with a different design it could be possible to reduce the number of exported functions to one, a big dispatcher. However, the number of total functions would hardly change.

**Comment by alexcrichton** [comment]
The "type size" metric is a rough approximation of "how long will it take to do a subtype check against this module". The goal of type sizes is to model how a linear description of a type may take an exponential amount of time to check for a subtype and protect validation against it. 

This means that for a core wasm module (and components) only imports/exports count. The "size" isn't really a concrete value mapping to something, so the "size" of a function is [basically the number of params/results](https://github.com/bytecodealliance/wasm-tools/blob/c892013426b5143b3e6108d2fc42ef825e63fe88/crates/wasmparser/src/validator/types.rs#LL445). The WIT signature you mentioned has one parameter and one result for core wasm modules meaning the core wasm module has a size of 4 per function, which with 20k functions gets you to 80k and I'm probably off-by-one somewhere to blow the 100k limit.

I've opened https://github.com/bytecodealliance/wasm-tools/pull/945 to bump the limit by 10x which would easily account for 45k functions. If you switch to a single dispatcher function it will also avoid hitting the limit that's happening today. I think we'll need more testing in the wild to see if a 1M limit sticks.

**Comment by alexcrichton** [comment]
Yes those are currently set at 1k and wouldn't accommodate a component with > 1000 imports/exports, but I think 1000 is probably much too low there. I sent https://github.com/bytecodealliance/wasm-tools/pull/947 to increase those limits.

**Comment by Finfalter** [comment]
@alexcrichton I retried with wasm-tools 1.0.28 and get a different error now:
```bash
$wasm-tools component new ./my-module.wasm -o my-component.wasm --adapt ./wasi_snapshot_preview1.wasm
Error: failed to encode a component from module

Caused by:
    0: failed to validate component output
    1: instantiation arguments size is out of bounds (at offset 0xf64d1e)
$:~/.../wasm32-unknown-unknown/release$ wasm-tools --version
wasm-tools 1.0.28
```
There seems to be still another parameter which set an upper boundary. Do you think it can be easily modified as well?
