### ISSUE TITLE
import `wasi-stderr` not defined

### ISSUE THREAD

**Issue by Finfalter** [bytecodealliance/wasm-tools#943]
I have a component which was built according to the notes on [wit-bindgen](https://github.com/bytecodealliance/wit-bindgen). I would like to run it with wasmtime and therefore followed these [notes](https://docs.rs/wasmtime/latest/wasmtime/component/macro.bindgen.html). 

When I `cargo run` I get the following error message: `import 'wasi-stderr' not defined`. Somehow, this feels consequent because in case I do `wasm-tools component wit ./my-component.wasm` against my component, I get the following interfaces
```bash
default world signals {
  import wasi-stderr: self.wasi-stderr
  import wasi-io: self.wasi-io
  import wasi-filesystem: self.wasi-filesystem
  import wasi-exit: self.wasi-exit
  import wasi-environment: self.wasi-environment
  export exports: self.exports
}
````
My problem is that I declared none of the imports in my **world.wit**. Also, currently I do not know how I could satisfy given imports. I browsed and discovered `WasiCtxBuilder` but it seems to be deprecated. 

Could you please briefly guide me how to either (or)

- get rid of the imports 
- satisfy given imports

**Comment by alexcrichton** [comment]
Yes WASI support is being actively worked on. You can use the `wasm32-unknown-unknown` target if you don't want WASI imports (or the functionality they provide). You can additionally follow [this repository](https://github.com/bytecodealliance/preview2-prototyping) for a work-in-progress implementation of WASI. This will be upstream in Wasmtime eventually.

**Comment by Finfalter** [comment]
Super, it works! 

Can you perhaps give me a further short general hint: what is the best channel to ask conceptual questions/questions of understanding? The question above was no real issue, yet, I have more questions like this one.

**Comment by pchickey** [comment]
https://bytecodealliance.zulipchat.com/ would probably be the appropriate venue
